"""auto_sync_schema

Revision ID: 026de40dafc4
Revises: a868c38cf516
Create Date: 2026-01-27 21:53:26.393908

"""

# destructive: approved
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "026de40dafc4"
down_revision: str | Sequence[str] | None = "a868c38cf516"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_user_tier_overrides_user_id"), table_name="user_tier_overrides")
  op.drop_table("user_tier_overrides")
  op.drop_index(op.f("ix_user_usage_logs_user_id"), table_name="user_usage_logs")
  op.drop_table("user_usage_logs")
  op.drop_table("user_usage_metrics")
  op.drop_table("subscription_tiers")
  op.drop_column("users", "is_approved")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("users", sa.Column("is_approved", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False))
  op.create_table(
    "subscription_tiers",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("max_file_upload_kb", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("highest_lesson_depth", postgresql.ENUM("highlights", "detailed", "training", name="lesson_depth"), autoincrement=False, nullable=True),
    sa.Column("max_sections_per_lesson", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("file_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("image_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("gen_sections_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("research_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("coach_mode_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column("coach_voice_tier", sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("subscription_tiers_pkey")),
    sa.UniqueConstraint("name", name=op.f("subscription_tiers_name_key"), postgresql_include=[], postgresql_nulls_not_distinct=False),
  )
  op.create_table(
    "user_usage_metrics",
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("subscription_tier_id", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("files_uploaded_count", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("images_uploaded_count", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("sections_generated_count", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("research_usage_count", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("last_updated", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"], name=op.f("user_usage_metrics_subscription_tier_id_fkey")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_usage_metrics_user_id_fkey")),
    sa.PrimaryKeyConstraint("user_id", name=op.f("user_usage_metrics_pkey")),
  )
  op.create_table(
    "user_usage_logs",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("action_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_usage_logs_user_id_fkey")),
    sa.PrimaryKeyConstraint("id", name=op.f("user_usage_logs_pkey")),
  )
  op.create_index(op.f("ix_user_usage_logs_user_id"), "user_usage_logs", ["user_id"], unique=False)
  op.create_table(
    "user_tier_overrides",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("starts_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column("max_file_upload_kb", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("file_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("image_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("gen_sections_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("research_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("coach_mode_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_tier_overrides_user_id_fkey")),
    sa.PrimaryKeyConstraint("id", name=op.f("user_tier_overrides_pkey")),
  )
  op.create_index(op.f("ix_user_tier_overrides_user_id"), "user_tier_overrides", ["user_id"], unique=False)
  # ### end Alembic commands ###
