rules:
  # Use Semgrep's curated rulesets for Python security
  - id: python-security-audit
    patterns:
      - pattern: $X
    message: Security audit ruleset
    languages: [python]
    severity: WARNING

# Configure which rulesets to use
# These will be specified via CLI: --config p/security-audit --config p/python --config p/owasp-top-ten
# This file is for custom rules specific to your application

# Example custom rule (commented out):
# rules:
#   - id: hardcoded-dgs-key
#     patterns:
#       - pattern: DGS_DEV_KEY = "..."
#     message: Hardcoded DGS_DEV_KEY found
#     languages: [python]
#     severity: ERROR
#     metadata:
#       cwe: "CWE-798: Use of Hard-coded Credentials"
#       owasp: "A07:2021 - Identification and Authentication Failures"

# Paths to exclude from scanning
paths:
  exclude:
    - "tests/"
    - ".venv/"
    - "postgres-data/"
    - "*.pyc"
    - "__pycache__/"
    - ".pytest_cache/"
    - ".ruff_cache/"
