AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploy the DGS FastAPI service to AWS Lambda with a Function URL and strict CORS.

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage identifier (for example, dev, staging, or prod).
  LogLevel:
    Type: String
    Default: info
    AllowedValues:
      - debug
      - info
      - warning
      - error
      - critical
    Description: Application log verbosity.
  FunctionName:
    Type: String
    Default: DgsFastApiFunction
    Description: Name of the deployed Lambda function.
  MemorySize:
    Type: Number
    Default: 512
    Description: Memory (in MB) allocated to the Lambda function.
  TimeoutSeconds:
    Type: Number
    Default: 30
    Description: Function timeout in seconds.
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: https://example.com
    Description: Comma-delimited list of allowed origins for the Function URL CORS policy.
  OpenRouterApiKey:
    Type: String
    NoEcho: true
    Description: API key for the OpenRouter provider.
  GeminiApiKey:
    Type: String
    NoEcho: true
    Description: API key for the Gemini provider.
  DgsDevKey:
    Type: String
    NoEcho: true
    Description: Shared secret for Phase 1 dev key access.
  LessonsTableName:
    Type: String
    Default: Lessons
    Description: DynamoDB table name for lesson storage.
  JobsTableName:
    Type: String
    Default: dgs_jobs
    Description: DynamoDB table name for job storage.
  JobsAllJobsIndexName:
    Type: String
    Default: jobs_all_jobs
    Description: GSI name for listing jobs.
  JobsIdempotencyIndexName:
    Type: String
    Default: jobs_idempotency
    Description: GSI name for idempotent lookups.
  JobsTtlSeconds:
    Type: Number
    Default: 604800
    Description: Optional TTL for job expiration in seconds.

Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - arm64
    MemorySize: !Ref MemorySize
    Timeout: !Ref TimeoutSeconds
    Environment:
      Variables:
        STAGE: !Ref Stage
        LOG_LEVEL: !Ref LogLevel
        OPENROUTER_API_KEY: !Ref OpenRouterApiKey
        GEMINI_API_KEY: !Ref GeminiApiKey
        DGS_DEV_KEY: !Ref DgsDevKey
        DGS_ALLOWED_ORIGINS: !Join [",", !Ref AllowedOrigins]
        DGS_DDB_TABLE: !Ref LessonsTableName
        DGS_JOBS_TABLE: !Ref JobsTableName
        DGS_JOBS_ALL_JOBS_INDEX: !Ref JobsAllJobsIndexName
        DGS_JOBS_IDEMPOTENCY_INDEX: !Ref JobsIdempotencyIndexName
        DGS_JOBS_TTL_SECONDS: !Ref JobsTtlSeconds

Resources:
  DgsFastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Description: FastAPI Lambda entrypoint for the Data Generation Service.
      CodeUri: ../dgs-backend
      Handler: lambda_handler.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref LessonsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
      Events:
        HttpApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: !Ref AllowedOrigins
          AllowCredentials: false
          AllowMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          AllowHeaders:
            - content-type
            - authorization
            - x-dgs-dev-key
          ExposeHeaders:
            - content-length
          MaxAge: 86400
      Tags:
        Service: dgs
        Layer: api

  LessonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref LessonsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lesson_id
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: lesson_id_index
          KeySchema:
            - AttributeName: lesson_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref JobsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1_pk
          AttributeType: S
        - AttributeName: gsi1_sk
          AttributeType: S
        - AttributeName: gsi2_pk
          AttributeType: S
        - AttributeName: gsi2_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Ref JobsAllJobsIndexName
          KeySchema:
            - AttributeName: gsi1_pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: !Ref JobsIdempotencyIndexName
          KeySchema:
            - AttributeName: gsi2_pk
              KeyType: HASH
            - AttributeName: gsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  JobsWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DgsJobsWorker
      Description: Background processor for queued lesson generation jobs.
      CodeUri: ../dgs-backend
      Handler: lambda_handler.process_jobs_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
      Environment:
        Variables:
          STAGE: !Ref Stage
          LOG_LEVEL: !Ref LogLevel
          DGS_DEV_KEY: !Ref DgsDevKey
          DGS_ALLOWED_ORIGINS: !Join [",", !Ref AllowedOrigins]
          DGS_DDB_TABLE: !Ref LessonsTableName
          DGS_JOBS_TABLE: !Ref JobsTableName
          DGS_JOBS_ALL_JOBS_INDEX: !Ref JobsAllJobsIndexName
          DGS_JOBS_IDEMPOTENCY_INDEX: !Ref JobsIdempotencyIndexName
          DGS_JOBS_TTL_SECONDS: !Ref JobsTtlSeconds

Outputs:
  FunctionUrl:
    Description: Public Function URL for invoking the FastAPI Lambda.
    Value: !GetAtt DgsFastApiFunctionUrl.FunctionUrl
  FunctionName:
    Description: Name of the deployed Lambda function.
    Value: !Ref DgsFastApiFunction
  AllowedCorsOrigins:
    Description: Origins permitted by the Function URL CORS configuration.
    Value: !Join [",", !Ref AllowedOrigins]
