AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploy the DGS FastAPI service to AWS Lambda with a Function URL and strict CORS.

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage identifier (for example, dev, staging, or prod).
  LogLevel:
    Type: String
    Default: info
    AllowedValues:
      - debug
      - info
      - warning
      - error
      - critical
    Description: Application log verbosity.
  FunctionName:
    Type: String
    Default: DgsFastApiFunction
    Description: Name of the deployed Lambda function.
  MemorySize:
    Type: Number
    Default: 512
    Description: Memory (in MB) allocated to the Lambda function.
  TimeoutSeconds:
    Type: Number
    Default: 30
    Description: Function timeout in seconds.
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: https://example.com
    Description: Comma-delimited list of allowed origins for the Function URL CORS policy.
  OpenRouterApiKey:
    Type: String
    NoEcho: true
    Description: API key for the OpenRouter provider.
  GeminiApiKey:
    Type: String
    NoEcho: true
    Description: API key for the Gemini provider.

Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - arm64
    MemorySize: !Ref MemorySize
    Timeout: !Ref TimeoutSeconds
    Environment:
      Variables:
        STAGE: !Ref Stage
        LOG_LEVEL: !Ref LogLevel
        OPENROUTER_API_KEY: !Ref OpenRouterApiKey
        GEMINI_API_KEY: !Ref GeminiApiKey

Resources:
  DgsFastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Description: FastAPI Lambda entrypoint for the Data Generation Service.
      CodeUri: ../dgs-backend
      Handler: lambda_handler.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HttpApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: !Ref AllowedOrigins
          AllowCredentials: false
          AllowMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          AllowHeaders:
            - content-type
            - authorization
          ExposeHeaders:
            - content-length
          MaxAge: 86400
      Tags:
        Service: dgs
        Layer: api

Outputs:
  FunctionUrl:
    Description: Public Function URL for invoking the FastAPI Lambda.
    Value: !GetAtt DgsFastApiFunctionUrl.FunctionUrl
  FunctionName:
    Description: Name of the deployed Lambda function.
    Value: !Ref DgsFastApiFunction
  AllowedCorsOrigins:
    Description: Origins permitted by the Function URL CORS configuration.
    Value: !Join [",", !Ref AllowedOrigins]
