AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DGS FastAPI Lambda deployment

Parameters:
  Stage:
    Type: String
    Default: local
    Description: Deployment stage identifier.
  LogLevel:
    Type: String
    Default: info
    Description: Log level for application runtime.
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: https://example.com
    Description: Comma-delimited list of allowed origins.
  DgsDevKey:
    Type: String
    NoEcho: true
    Description: Shared secret for Phase 1 dev key access.
  LessonsTableName:
    Type: String
    Default: Lessons
    Description: DynamoDB table name for lesson storage.
  JobsTableName:
    Type: String
    Default: dgs_jobs
    Description: DynamoDB table name for job storage.
  JobsAllJobsIndexName:
    Type: String
    Default: jobs_all_jobs
    Description: GSI name for listing all jobs.
  JobsIdempotencyIndexName:
    Type: String
    Default: jobs_idempotency
    Description: GSI name for idempotency tracking.
  JobsTtlSeconds:
    Type: Number
    Default: 604800
    Description: Optional TTL for job expiration in seconds.

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256

Resources:
  DgsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DgsApiFunction
      CodeUri: ../dgs-backend
      Handler: lambda_handler.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref LessonsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          STAGE: !Ref Stage
          LOG_LEVEL: !Ref LogLevel
          DGS_DEV_KEY: !Ref DgsDevKey
          DGS_ALLOWED_ORIGINS: !Join [",", !Ref AllowedOrigins]
          DGS_DDB_TABLE: !Ref LessonsTableName
          DGS_JOBS_TABLE: !Ref JobsTableName
          DGS_JOBS_ALL_JOBS_INDEX: !Ref JobsAllJobsIndexName
          DGS_JOBS_IDEMPOTENCY_INDEX: !Ref JobsIdempotencyIndexName
          DGS_JOBS_TTL_SECONDS: !Ref JobsTtlSeconds

  LessonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref LessonsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lesson_id
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: lesson_id_index
          KeySchema:
            - AttributeName: lesson_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref JobsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1_pk
          AttributeType: S
        - AttributeName: gsi1_sk
          AttributeType: S
        - AttributeName: gsi2_pk
          AttributeType: S
        - AttributeName: gsi2_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: !Ref JobsAllJobsIndexName
          KeySchema:
            - AttributeName: gsi1_pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: !Ref JobsIdempotencyIndexName
          KeySchema:
            - AttributeName: gsi2_pk
              KeyType: HASH
            - AttributeName: gsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  JobsWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DgsJobsWorker
      CodeUri: ../dgs-backend
      Handler: lambda_handler.process_jobs_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
      Environment:
        Variables:
          STAGE: !Ref Stage
          LOG_LEVEL: !Ref LogLevel
          DGS_DEV_KEY: !Ref DgsDevKey
          DGS_ALLOWED_ORIGINS: !Join [",", !Ref AllowedOrigins]
          DGS_DDB_TABLE: !Ref LessonsTableName
          DGS_JOBS_TABLE: !Ref JobsTableName
          DGS_JOBS_ALL_JOBS_INDEX: !Ref JobsAllJobsIndexName
          DGS_JOBS_IDEMPOTENCY_INDEX: !Ref JobsIdempotencyIndexName
          DGS_JOBS_TTL_SECONDS: !Ref JobsTtlSeconds

Outputs:
  FunctionUrl:
    Description: Function URL endpoint for the Lambda.
    Value: !GetAtt DgsApiFunctionUrl.FunctionUrl
  FunctionUrlArn:
    Description: ARN for the Lambda Function URL.
    Value: !GetAtt DgsApiFunctionUrl.FunctionUrlArn
