"""remove_is_approved

Revision ID: 1f3c81587763
Revises: 5d3a0b7c9f21
Create Date: 2026-01-27 15:05:15.947947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f3c81587763"
down_revision: Union[str, Sequence[str], None] = "5d3a0b7c9f21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("users", "is_approved")
  op.drop_column("users", "is_admin")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("users", sa.Column("is_admin", sa.Boolean(), autoincrement=False, nullable=False, server_default="false"))
  op.add_column("users", sa.Column("is_approved", sa.Boolean(), autoincrement=False, nullable=False, server_default="false"))
  # ### end Alembic commands ###
