"""Add profession column to users

Revision ID: 241feda2db69
Revises:
Create Date: 2026-01-19 21:17:48.385511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "241feda2db69"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("users", sa.Column("profession", sa.String(), nullable=True))
  op.add_column("users", sa.Column("city", sa.String(), nullable=True))
  op.add_column("users", sa.Column("country", sa.String(), nullable=True))
  op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
  op.add_column("users", sa.Column("photo_url", sa.String(), nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("users", "photo_url")
  op.drop_column("users", "age")
  op.drop_column("users", "country")
  op.drop_column("users", "city")
  op.drop_column("users", "profession")
  # ### end Alembic commands ###
