"""auto_sync_schema

Revision ID: 4c3a547433f7
Revises: 7a3e4e6e9a6b
Create Date: 2026-01-27 04:58:19.026482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c3a547433f7"
down_revision: Union[str, Sequence[str], None] = "7a3e4e6e9a6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_user_tier_overrides_user_id"), table_name="user_tier_overrides")
  op.drop_table("user_tier_overrides")
  op.drop_index(op.f("ix_user_usage_logs_user_id"), table_name="user_usage_logs")
  op.drop_table("user_usage_logs")
  op.drop_table("user_usage_metrics")
  op.drop_table("subscription_tiers")
  op.alter_column("dgs_jobs", "job_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "phase", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "subphase", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_title", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "retry_parent_job_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "created_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "updated_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "completed_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "idempotency_key", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.drop_index(op.f("dgs_jobs_idempotency_idx"), table_name="dgs_jobs")
  op.drop_index(op.f("dgs_jobs_status_created_idx"), table_name="dgs_jobs")
  op.create_index(op.f("ix_dgs_jobs_idempotency_key"), "dgs_jobs", ["idempotency_key"], unique=False)
  op.alter_column("dgs_lessons", "lesson_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "topic", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "title", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "created_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "schema_version", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "prompt_version", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_a", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_a", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_b", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_b", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "idempotency_key", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.drop_index(op.f("dgs_lessons_idempotency_idx"), table_name="dgs_lessons")
  op.create_index(op.f("ix_dgs_lessons_idempotency_key"), "dgs_lessons", ["idempotency_key"], unique=False)
  op.alter_column("llm_call_audit", "id", existing_type=sa.UUID(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True, existing_server_default=sa.text("now()"))
  op.alter_column("llm_call_audit", "agent", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "provider", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "model", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "lesson_topic", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "request_type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "purpose", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "call_index", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "job_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.drop_index(op.f("llm_call_audit_agent_idx"), table_name="llm_call_audit")
  op.drop_index(op.f("llm_call_audit_created_at_idx"), table_name="llm_call_audit")
  op.drop_index(op.f("llm_call_audit_model_idx"), table_name="llm_call_audit")
  op.drop_index(op.f("llm_call_audit_topic_idx"), table_name="llm_call_audit")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(op.f("llm_call_audit_topic_idx"), "llm_call_audit", ["lesson_topic"], unique=False)
  op.create_index(op.f("llm_call_audit_model_idx"), "llm_call_audit", ["model"], unique=False)
  op.create_index(op.f("llm_call_audit_created_at_idx"), "llm_call_audit", ["created_at"], unique=False)
  op.create_index(op.f("llm_call_audit_agent_idx"), "llm_call_audit", ["agent"], unique=False)
  op.alter_column("llm_call_audit", "status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "job_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "call_index", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "purpose", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "request_type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "lesson_topic", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "model", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "provider", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "agent", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False, existing_server_default=sa.text("now()"))
  op.alter_column("llm_call_audit", "id", existing_type=sa.String(), type_=sa.UUID(), existing_nullable=False)
  op.drop_index(op.f("ix_dgs_lessons_idempotency_key"), table_name="dgs_lessons")
  op.create_index(op.f("dgs_lessons_idempotency_idx"), "dgs_lessons", ["idempotency_key"], unique=False)
  op.alter_column("dgs_lessons", "idempotency_key", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_lessons", "status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_b", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_b", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_a", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_a", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "prompt_version", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "schema_version", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "created_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "title", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "topic", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "lesson_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.drop_index(op.f("ix_dgs_jobs_idempotency_key"), table_name="dgs_jobs")
  op.create_index(op.f("dgs_jobs_status_created_idx"), "dgs_jobs", ["status", "created_at"], unique=False)
  op.create_index(op.f("dgs_jobs_idempotency_idx"), "dgs_jobs", ["idempotency_key"], unique=False)
  op.alter_column("dgs_jobs", "idempotency_key", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "completed_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "updated_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "created_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "retry_parent_job_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_title", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "subphase", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "phase", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "job_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.create_table(
    "subscription_tiers",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("max_file_upload_kb", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("highest_lesson_depth", postgresql.ENUM("highlights", "detailed", "training", name="lesson_depth"), autoincrement=False, nullable=True),
    sa.Column("max_sections_per_lesson", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("file_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("image_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("gen_sections_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("coach_mode_enabled", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    sa.Column("coach_voice_tier", sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("subscription_tiers_pkey")),
    sa.UniqueConstraint("name", name=op.f("subscription_tiers_name_key"), postgresql_include=[], postgresql_nulls_not_distinct=False),
  )
  op.create_table(
    "user_usage_metrics",
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("subscription_tier_id", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("files_uploaded_count", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    sa.Column("images_uploaded_count", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    sa.Column("sections_generated_count", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
    sa.Column("last_updated", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"], name=op.f("user_usage_metrics_subscription_tier_id_fkey")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_usage_metrics_user_id_fkey")),
    sa.PrimaryKeyConstraint("user_id", name=op.f("user_usage_metrics_pkey")),
  )
  op.create_table(
    "user_usage_logs",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("action_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("quantity", sa.INTEGER(), server_default=sa.text("1"), autoincrement=False, nullable=False),
    sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_usage_logs_user_id_fkey")),
    sa.PrimaryKeyConstraint("id", name=op.f("user_usage_logs_pkey")),
  )
  op.create_index(op.f("ix_user_usage_logs_user_id"), "user_usage_logs", ["user_id"], unique=False)
  op.create_table(
    "user_tier_overrides",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("starts_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column("max_file_upload_kb", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("file_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("image_upload_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("gen_sections_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("coach_mode_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_tier_overrides_user_id_fkey")),
    sa.PrimaryKeyConstraint("id", name=op.f("user_tier_overrides_pkey")),
  )
  op.create_index(op.f("ix_user_tier_overrides_user_id"), "user_tier_overrides", ["user_id"], unique=False)
  # ### end Alembic commands ###
