"""Adopt existing tables to SQLAlchemy (Corrected)

Revision ID: 989029857d49
Revises: 241feda2db69
Create Date: 2026-01-19 23:05:42.326213

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "989029857d49"
down_revision: str | Sequence[str] | None = "241feda2db69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("dgs_storage_meta")
  op.drop_table("llm_audit_meta")
  op.alter_column("dgs_jobs", "job_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "phase", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "subphase", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_title", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "retry_parent_job_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "created_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "updated_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_jobs", "completed_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("dgs_jobs", "idempotency_key", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.drop_index(op.f("dgs_jobs_idempotency_idx"), table_name="dgs_jobs")
  op.drop_index(op.f("dgs_jobs_status_created_idx"), table_name="dgs_jobs")
  op.create_index(op.f("ix_dgs_jobs_idempotency_key"), "dgs_jobs", ["idempotency_key"], unique=False)
  op.alter_column("dgs_lessons", "lesson_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "topic", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "title", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "created_at", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "schema_version", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "prompt_version", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_a", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_a", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_b", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_b", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("dgs_lessons", "idempotency_key", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.drop_index(op.f("dgs_lessons_idempotency_idx"), table_name="dgs_lessons")
  op.create_index(op.f("ix_dgs_lessons_idempotency_key"), "dgs_lessons", ["idempotency_key"], unique=False)
  op.alter_column("llm_call_audit", "id", existing_type=sa.UUID(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True, existing_server_default=sa.text("now()"))
  op.alter_column("llm_call_audit", "agent", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "provider", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "model", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "lesson_topic", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "request_type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.alter_column("llm_call_audit", "purpose", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "call_index", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "job_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
  op.alter_column("llm_call_audit", "status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
  op.drop_index(op.f("llm_call_audit_agent_idx"), table_name="llm_call_audit")
  op.drop_index(op.f("llm_call_audit_created_at_idx"), table_name="llm_call_audit")
  op.drop_index(op.f("llm_call_audit_model_idx"), table_name="llm_call_audit")
  op.drop_index(op.f("llm_call_audit_topic_idx"), table_name="llm_call_audit")
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(op.f("llm_call_audit_topic_idx"), "llm_call_audit", ["lesson_topic"], unique=False)
  op.create_index(op.f("llm_call_audit_model_idx"), "llm_call_audit", ["model"], unique=False)
  op.create_index(op.f("llm_call_audit_created_at_idx"), "llm_call_audit", ["created_at"], unique=False)
  op.create_index(op.f("llm_call_audit_agent_idx"), "llm_call_audit", ["agent"], unique=False)
  op.alter_column("llm_call_audit", "status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "job_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "call_index", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "purpose", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "request_type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "lesson_topic", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("llm_call_audit", "model", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "provider", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "agent", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("llm_call_audit", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False, existing_server_default=sa.text("now()"))
  op.alter_column("llm_call_audit", "id", existing_type=sa.String(), type_=sa.UUID(), existing_nullable=False)
  op.drop_index(op.f("ix_dgs_lessons_idempotency_key"), table_name="dgs_lessons")
  op.create_index(op.f("dgs_lessons_idempotency_idx"), "dgs_lessons", ["idempotency_key"], unique=False)
  op.alter_column("dgs_lessons", "idempotency_key", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_lessons", "status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_b", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_b", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "model_a", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "provider_a", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "prompt_version", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "schema_version", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "created_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "title", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "topic", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_lessons", "lesson_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.drop_index(op.f("ix_dgs_jobs_idempotency_key"), table_name="dgs_jobs")
  op.create_index(op.f("dgs_jobs_status_created_idx"), "dgs_jobs", ["status", "created_at"], unique=False)
  op.create_index(op.f("dgs_jobs_idempotency_idx"), "dgs_jobs", ["idempotency_key"], unique=False)
  op.alter_column("dgs_jobs", "idempotency_key", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "completed_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "updated_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "created_at", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "retry_parent_job_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_title", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "current_section_status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "subphase", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
  op.alter_column("dgs_jobs", "phase", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.alter_column("dgs_jobs", "job_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
  op.create_table(
    "llm_audit_meta",
    sa.Column("key", sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint("key", name=op.f("llm_audit_meta_pkey")),
  )
  op.create_table(
    "dgs_storage_meta",
    sa.Column("key", sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint("key", name=op.f("dgs_storage_meta_pkey")),
  )
  # ### end Alembic commands ###
