"""initial_schema_baseline

Revision ID: 0b7d3f4f725b
Revises:
Create Date: 2026-02-10 17:07:01.210285

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.core.migration_guards import column_exists, guarded_create_index, guarded_create_table, guarded_drop_index, guarded_drop_table, table_exists
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0b7d3f4f725b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TIMESTAMP_UPDATED_AT_TABLES = ["users", "runtime_config_values", "organization_feature_flags", "subscription_tier_feature_flags", "user_feature_flag_overrides", "illustrations", "user_quota_buckets", "data_transfer_runs"]

_STRING_DEFAULT_EXPR = "to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"


def _set_default(*, table_name: str, column_name: str, expression: str) -> None:
  """Set a column default when the target table/column exists."""
  # Guard against environments with partial schema history.
  if not table_exists(table_name=table_name) or not column_exists(table_name=table_name, column_name=column_name):
    return
  guarded_sql = f'ALTER TABLE "{table_name}" ALTER COLUMN "{column_name}" SET DEFAULT {expression}'
  op.execute(guarded_sql)


def _create_update_trigger(*, table_name: str, trigger_name: str, function_name: str) -> None:
  """Create a BEFORE UPDATE trigger for updated_at when schema is present."""
  # Only attach triggers to tables that actually have updated_at.
  if not table_exists(table_name=table_name) or not column_exists(table_name=table_name, column_name="updated_at"):
    return
  op.execute(f'DROP TRIGGER IF EXISTS "{trigger_name}" ON "{table_name}"')
  op.execute(f'CREATE TRIGGER "{trigger_name}" BEFORE UPDATE ON "{table_name}" FOR EACH ROW EXECUTE FUNCTION "{function_name}"()')


def upgrade() -> None:
  """Upgrade schema."""
  # Use guarded_* helpers so migrations are idempotent on existing schemas.
  # ### commands auto generated by Alembic - please adjust! ###
  guarded_create_table(
    "tutor_audios",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("section_number", sa.Integer(), nullable=False),
    sa.Column("subsection_index", sa.Integer(), nullable=False),
    sa.Column("text_content", sa.Text(), nullable=True),
    sa.Column("audio_data", sa.LargeBinary(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_tutor_audios_id"), "tutor_audios", ["id"], unique=False)
  guarded_create_index(op.f("ix_tutor_audios_job_id"), "tutor_audios", ["job_id"], unique=False)
  guarded_create_table(
    "feature_flags",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("default_enabled", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
  guarded_create_table(
    "fenster_widgets",
    sa.Column("fenster_id", sa.Uuid(), nullable=False),
    sa.Column("type", sa.Enum("INLINE_BLOB", "CDN_URL", name="fensterwidgettype"), nullable=False),
    sa.Column("content", sa.LargeBinary(), nullable=True),
    sa.Column("url", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("fenster_id"),
  )
  guarded_create_table(
    "illustrations",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("storage_bucket", sa.Text(), nullable=False),
    sa.Column("storage_object_name", sa.Text(), nullable=False),
    sa.Column("mime_type", sa.String(), nullable=False),
    sa.Column("caption", sa.Text(), nullable=False),
    sa.Column("ai_prompt", sa.Text(), nullable=False),
    sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), nullable=False),
    sa.Column("regenerate", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_illustrations_storage_object_name"), "illustrations", ["storage_object_name"], unique=False)
  guarded_create_table(
    "jobs",
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("job_kind", sa.String(), nullable=False),
    sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("parent_job_id", sa.String(), nullable=True),
    sa.Column("lesson_id", sa.String(), nullable=True),
    sa.Column("section_id", sa.Integer(), nullable=True),
    sa.Column("target_agent", sa.String(), nullable=True),
    sa.Column("phase", sa.String(), nullable=False),
    sa.Column("subphase", sa.String(), nullable=True),
    sa.Column("expected_sections", sa.Integer(), nullable=True),
    sa.Column("completed_sections", sa.Integer(), nullable=True),
    sa.Column("completed_section_indexes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("current_section_index", sa.Integer(), nullable=True),
    sa.Column("current_section_status", sa.String(), nullable=True),
    sa.Column("current_section_retry_count", sa.Integer(), nullable=True),
    sa.Column("current_section_title", sa.String(), nullable=True),
    sa.Column("retry_count", sa.Integer(), nullable=True),
    sa.Column("max_retries", sa.Integer(), nullable=True),
    sa.Column("retry_sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("retry_agents", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("retry_parent_job_id", sa.String(), nullable=True),
    sa.Column("total_steps", sa.Integer(), nullable=True),
    sa.Column("completed_steps", sa.Integer(), nullable=True),
    sa.Column("progress", sa.Double(), nullable=True),
    sa.Column("logs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.String(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"), nullable=False),
    sa.Column("updated_at", sa.String(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"), nullable=False),
    sa.Column("completed_at", sa.String(), nullable=True),
    sa.Column("ttl", sa.Integer(), nullable=True),
    sa.Column("idempotency_key", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("job_id"),
    sa.UniqueConstraint("user_id", "job_kind", "idempotency_key", name="ux_jobs_user_kind_idempotency"),
  )
  guarded_create_index(op.f("ix_jobs_idempotency_key"), "jobs", ["idempotency_key"], unique=False)
  guarded_create_index(op.f("ix_jobs_job_kind"), "jobs", ["job_kind"], unique=False)
  guarded_create_index(op.f("ix_jobs_lesson_id"), "jobs", ["lesson_id"], unique=False)
  guarded_create_index(op.f("ix_jobs_parent_job_id"), "jobs", ["parent_job_id"], unique=False)
  guarded_create_index(op.f("ix_jobs_section_id"), "jobs", ["section_id"], unique=False)
  guarded_create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
  guarded_create_table(
    "lessons",
    sa.Column("lesson_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("topic", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("created_at", sa.String(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"), nullable=False),
    sa.Column("schema_version", sa.String(), nullable=False),
    sa.Column("prompt_version", sa.String(), nullable=False),
    sa.Column("provider_a", sa.String(), nullable=False),
    sa.Column("model_a", sa.String(), nullable=False),
    sa.Column("provider_b", sa.String(), nullable=False),
    sa.Column("model_b", sa.String(), nullable=False),
    sa.Column("lesson_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("latency_ms", sa.Integer(), nullable=False),
    sa.Column("idempotency_key", sa.String(), nullable=True),
    sa.Column("tags", sa.ARRAY(sa.Text()), nullable=True),
    sa.Column("is_archived", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("lesson_id"),
  )
  guarded_create_index(op.f("ix_lessons_idempotency_key"), "lessons", ["idempotency_key"], unique=False)
  guarded_create_index(op.f("ix_lessons_user_id"), "lessons", ["user_id"], unique=False)
  guarded_create_table(
    "llm_call_audit",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("timestamp_request", sa.DateTime(timezone=True), nullable=False),
    sa.Column("timestamp_response", sa.DateTime(timezone=True), nullable=True),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("duration_ms", sa.Integer(), nullable=False),
    sa.Column("agent", sa.String(), nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("model", sa.String(), nullable=False),
    sa.Column("lesson_topic", sa.String(), nullable=True),
    sa.Column("request_payload", sa.Text(), nullable=False),
    sa.Column("response_payload", sa.Text(), nullable=True),
    sa.Column("prompt_tokens", sa.Integer(), nullable=True),
    sa.Column("completion_tokens", sa.Integer(), nullable=True),
    sa.Column("total_tokens", sa.Integer(), nullable=True),
    sa.Column("request_type", sa.String(), nullable=False),
    sa.Column("purpose", sa.String(), nullable=True),
    sa.Column("call_index", sa.String(), nullable=True),
    sa.Column("job_id", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_table(
    "organizations",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  guarded_create_table(
    "permissions",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("slug", sa.String(), nullable=False),
    sa.Column("display_name", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("slug"),
  )
  guarded_create_table(
    "roles",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("level", sa.Enum("GLOBAL", "TENANT", name="role_level"), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  guarded_create_table(
    "subscription_tiers",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("max_file_upload_kb", sa.Integer(), nullable=True),
    sa.Column("highest_lesson_depth", sa.Enum("highlights", "detailed", "training", name="lesson_depth"), nullable=True),
    sa.Column("max_sections_per_lesson", sa.Integer(), nullable=True),
    sa.Column("file_upload_quota", sa.Integer(), nullable=True),
    sa.Column("image_upload_quota", sa.Integer(), nullable=True),
    sa.Column("gen_sections_quota", sa.Integer(), nullable=True),
    sa.Column("research_quota", sa.Integer(), nullable=True),
    sa.Column("concurrent_lesson_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_research_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_writing_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_tutor_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("tutor_mode_enabled", sa.Boolean(), nullable=False),
    sa.Column("tutor_voice_tier", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  guarded_create_table(
    "organization_feature_flags",
    sa.Column("org_id", sa.Uuid(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.PrimaryKeyConstraint("org_id", "feature_flag_id"),
  )
  guarded_create_table(
    "role_permissions",
    sa.Column("role_id", sa.Uuid(), nullable=False),
    sa.Column("permission_id", sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"]),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
    sa.PrimaryKeyConstraint("role_id", "permission_id"),
  )
  guarded_create_table(
    "sections",
    sa.Column("section_id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("lesson_id", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("order_index", sa.Integer(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("content_shorthand", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(["lesson_id"], ["lessons.lesson_id"]),
    sa.PrimaryKeyConstraint("section_id"),
  )
  guarded_create_index(op.f("ix_sections_lesson_id"), "sections", ["lesson_id"], unique=False)
  guarded_create_table(
    "subscription_tier_feature_flags",
    sa.Column("subscription_tier_id", sa.Integer(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.PrimaryKeyConstraint("subscription_tier_id", "feature_flag_id"),
  )
  guarded_create_table(
    "users",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("firebase_uid", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=True),
    sa.Column("provider", sa.String(), nullable=True),
    sa.Column("role_id", sa.Uuid(), nullable=False),
    sa.Column("org_id", sa.Uuid(), nullable=True),
    sa.Column("status", sa.Enum("PENDING", "APPROVED", "DISABLED", "REJECTED", name="user_status"), nullable=False),
    sa.Column("auth_method", sa.Enum("GOOGLE_SSO", "NATIVE", name="auth_method"), nullable=False),
    sa.Column("profession", sa.String(), nullable=True),
    sa.Column("city", sa.String(), nullable=True),
    sa.Column("country", sa.String(), nullable=True),
    sa.Column("age", sa.Integer(), nullable=True),
    sa.Column("photo_url", sa.String(), nullable=True),
    sa.Column("gender", sa.String(), nullable=True),
    sa.Column("gender_other", sa.String(), nullable=True),
    sa.Column("occupation", sa.String(), nullable=True),
    sa.Column("topics_of_interest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("intended_use", sa.String(), nullable=True),
    sa.Column("intended_use_other", sa.String(), nullable=True),
    sa.Column("primary_language", sa.String(), nullable=True),
    sa.Column("secondary_language", sa.String(), nullable=True),
    sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
    sa.Column("is_discarded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    sa.Column("discarded_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("discarded_by", sa.Uuid(), nullable=True),
    sa.Column("accepted_terms_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("accepted_privacy_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("terms_version", sa.String(), nullable=True),
    sa.Column("privacy_version", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  guarded_create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
  guarded_create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
  guarded_create_table(
    "data_transfer_runs",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("run_type", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("requested_by", sa.UUID(), nullable=False),
    sa.Column("source_export_run_id", sa.UUID(), nullable=True),
    sa.Column("include_illustrations", sa.Boolean(), nullable=False),
    sa.Column("include_audios", sa.Boolean(), nullable=False),
    sa.Column("include_fensters", sa.Boolean(), nullable=False),
    sa.Column("separate_zips", sa.Boolean(), nullable=False),
    sa.Column("dry_run", sa.Boolean(), nullable=False),
    sa.Column("password_plaintext", sa.Text(), nullable=False),
    sa.Column("gcs_bucket", sa.String(), nullable=False),
    sa.Column("artifacts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("filters_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("idempotency_key", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["requested_by"], ["users.id"]),
    sa.ForeignKeyConstraint(["source_export_run_id"], ["data_transfer_runs.id"]),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("run_type", "requested_by", "idempotency_key", name="ux_data_transfer_runs_type_user_idempotency"),
  )
  guarded_create_index(op.f("ix_data_transfer_runs_job_id"), "data_transfer_runs", ["job_id"], unique=True)
  guarded_create_index(op.f("ix_data_transfer_runs_requested_by"), "data_transfer_runs", ["requested_by"], unique=False)
  guarded_create_index(op.f("ix_data_transfer_runs_run_type"), "data_transfer_runs", ["run_type"], unique=False)
  guarded_create_index(op.f("ix_data_transfer_runs_source_export_run_id"), "data_transfer_runs", ["source_export_run_id"], unique=False)
  guarded_create_index(op.f("ix_data_transfer_runs_status"), "data_transfer_runs", ["status"], unique=False)
  guarded_create_table(
    "email_delivery_logs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=True),
    sa.Column("to_address", sa.String(), nullable=False),
    sa.Column("template_id", sa.String(), nullable=False),
    sa.Column("placeholders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("provider_message_id", sa.String(), nullable=True),
    sa.Column("provider_request_id", sa.String(), nullable=True),
    sa.Column("provider_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_email_delivery_logs_provider_message_id"), "email_delivery_logs", ["provider_message_id"], unique=False)
  guarded_create_index(op.f("ix_email_delivery_logs_provider_request_id"), "email_delivery_logs", ["provider_request_id"], unique=False)
  guarded_create_index(op.f("ix_email_delivery_logs_template_id"), "email_delivery_logs", ["template_id"], unique=False)
  guarded_create_index(op.f("ix_email_delivery_logs_to_address"), "email_delivery_logs", ["to_address"], unique=False)
  guarded_create_index(op.f("ix_email_delivery_logs_user_id"), "email_delivery_logs", ["user_id"], unique=False)
  guarded_create_table(
    "llm_audit_logs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("prompt_summary", sa.Text(), nullable=True),
    sa.Column("model_name", sa.String(), nullable=False),
    sa.Column("tokens_used", sa.Integer(), nullable=True),
    sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("status", sa.String(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_table(
    "notifications",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("template_id", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("body", sa.Text(), nullable=False),
    sa.Column("data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("read", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_notifications_template_id"), "notifications", ["template_id"], unique=False)
  guarded_create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
  guarded_create_table(
    "runtime_config_values",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key", sa.String(), nullable=False),
    sa.Column("scope", sa.Enum("GLOBAL", "TIER", "TENANT", "USER", name="runtime_config_scope"), nullable=False),
    sa.Column("org_id", sa.Uuid(), nullable=True),
    sa.Column("subscription_tier_id", sa.Integer(), nullable=True),
    sa.Column("user_id", sa.Uuid(), nullable=True),
    sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_runtime_config_values_key"), "runtime_config_values", ["key"], unique=False)
  guarded_create_index(op.f("ix_runtime_config_values_org_id"), "runtime_config_values", ["org_id"], unique=False)
  guarded_create_index(op.f("ix_runtime_config_values_scope"), "runtime_config_values", ["scope"], unique=False)
  guarded_create_index(op.f("ix_runtime_config_values_subscription_tier_id"), "runtime_config_values", ["subscription_tier_id"], unique=False)
  guarded_create_index(op.f("ix_runtime_config_values_user_id"), "runtime_config_values", ["user_id"], unique=False)
  guarded_create_index("ux_runtime_config_values_global", "runtime_config_values", ["key"], unique=True, postgresql_where=sa.text("scope = 'GLOBAL'"))
  guarded_create_index("ux_runtime_config_values_tenant", "runtime_config_values", ["key", "org_id"], unique=True, postgresql_where=sa.text("scope = 'TENANT'"))
  guarded_create_index("ux_runtime_config_values_tier", "runtime_config_values", ["key", "subscription_tier_id"], unique=True, postgresql_where=sa.text("scope = 'TIER'"))
  guarded_create_index("ux_runtime_config_values_user", "runtime_config_values", ["key", "user_id"], unique=True, postgresql_where=sa.text("scope = 'USER'"))
  guarded_create_table(
    "section_errors",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("section_id", sa.Integer(), nullable=False),
    sa.Column("error_index", sa.Integer(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=False),
    sa.Column("error_path", sa.Text(), nullable=True),
    sa.Column("section_scope", sa.String(), nullable=True),
    sa.Column("subsection_index", sa.Integer(), nullable=True),
    sa.Column("item_index", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_section_errors_section_id"), "section_errors", ["section_id"], unique=False)
  guarded_create_table(
    "section_illustrations",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("section_id", sa.Integer(), nullable=False),
    sa.Column("illustration_id", sa.BigInteger(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["illustration_id"], ["illustrations.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_section_illustrations_illustration_id"), "section_illustrations", ["illustration_id"], unique=False)
  guarded_create_index(op.f("ix_section_illustrations_section_id"), "section_illustrations", ["section_id"], unique=False)
  guarded_create_table(
    "subjective_input_widgets",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("section_id", sa.Integer(), nullable=False),
    sa.Column("widget_type", sa.String(), nullable=False),
    sa.Column("ai_prompt", sa.Text(), nullable=False),
    sa.Column("wordlist", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_subjective_input_widgets_section_id"), "subjective_input_widgets", ["section_id"], unique=False)
  guarded_create_table(
    "user_feature_flag_overrides",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("starts_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "feature_flag_id", name="ux_user_feature_flag_overrides_user_flag"),
  )
  guarded_create_index(op.f("ix_user_feature_flag_overrides_feature_flag_id"), "user_feature_flag_overrides", ["feature_flag_id"], unique=False)
  guarded_create_index(op.f("ix_user_feature_flag_overrides_user_id"), "user_feature_flag_overrides", ["user_id"], unique=False)
  guarded_create_table(
    "user_quota_buckets",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("metric_key", sa.String(), nullable=False),
    sa.Column("period", postgresql.ENUM("WEEK", "MONTH", name="quota_period"), nullable=False),
    sa.Column("period_start", sa.Date(), nullable=False),
    sa.Column("used", sa.BigInteger(), server_default="0", nullable=False),
    sa.Column("reserved", sa.BigInteger(), server_default="0", nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_user_quota_buckets_metric_key"), "user_quota_buckets", ["metric_key"], unique=False)
  guarded_create_index(op.f("ix_user_quota_buckets_user_id"), "user_quota_buckets", ["user_id"], unique=False)
  guarded_create_table(
    "user_quota_reservations",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("metric_key", sa.String(), nullable=False),
    sa.Column("period", postgresql.ENUM("WEEK", "MONTH", name="quota_period"), nullable=False),
    sa.Column("period_start", sa.Date(), nullable=False),
    sa.Column("quantity", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("section_index", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "metric_key", "period", "period_start", "job_id", "section_index", name="ux_quota_reservation_key"),
  )
  guarded_create_index(op.f("ix_user_quota_reservations_job_id"), "user_quota_reservations", ["job_id"], unique=False)
  guarded_create_index(op.f("ix_user_quota_reservations_metric_key"), "user_quota_reservations", ["metric_key"], unique=False)
  guarded_create_index(op.f("ix_user_quota_reservations_user_id"), "user_quota_reservations", ["user_id"], unique=False)
  guarded_create_table(
    "user_tier_overrides",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("max_file_upload_kb", sa.Integer(), nullable=True),
    sa.Column("file_upload_quota", sa.Integer(), nullable=True),
    sa.Column("image_upload_quota", sa.Integer(), nullable=True),
    sa.Column("gen_sections_quota", sa.Integer(), nullable=True),
    sa.Column("research_quota", sa.Integer(), nullable=True),
    sa.Column("concurrent_lesson_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_research_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_writing_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_tutor_limit", sa.Integer(), nullable=True),
    sa.Column("tutor_mode_enabled", sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_user_tier_overrides_user_id"), "user_tier_overrides", ["user_id"], unique=False)
  guarded_create_table(
    "user_usage_logs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("action_type", sa.String(), nullable=False),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_user_usage_logs_user_id"), "user_usage_logs", ["user_id"], unique=False)
  guarded_create_table(
    "user_usage_metrics",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("subscription_tier_id", sa.Integer(), nullable=False),
    sa.Column("files_uploaded_count", sa.Integer(), nullable=False),
    sa.Column("images_uploaded_count", sa.Integer(), nullable=False),
    sa.Column("sections_generated_count", sa.Integer(), nullable=False),
    sa.Column("research_usage_count", sa.Integer(), nullable=False),
    sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("user_id"),
  )
  guarded_create_table(
    "web_push_subscriptions",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("endpoint", sa.Text(), nullable=False),
    sa.Column("p256dh", sa.Text(), nullable=False),
    sa.Column("auth", sa.Text(), nullable=False),
    sa.Column("user_agent", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  guarded_create_index(op.f("ix_web_push_subscriptions_user_id"), "web_push_subscriptions", ["user_id"], unique=False)
  guarded_create_index("ux_web_push_subscriptions_endpoint", "web_push_subscriptions", ["endpoint"], unique=True)
  # ### end Alembic commands ###

  # Create trigger function for timestamptz updated_at columns.
  op.execute(
    """
        CREATE OR REPLACE FUNCTION public.set_updated_at_timestamptz()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
            NEW.updated_at := now();
          END IF;
          RETURN NEW;
        END;
        $$;
        """
  )

  # Create trigger function for legacy text updated_at columns.
  op.execute(
    """
        CREATE OR REPLACE FUNCTION public.set_updated_at_iso8601_text()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
          IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
            NEW.updated_at := to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD"T"HH24:MI:SS"Z"');
          END IF;
          RETURN NEW;
        END;
        $$;
        """
  )

  # Ensure DB-level create defaults exist for legacy text timestamp columns.
  _set_default(table_name="lessons", column_name="created_at", expression=_STRING_DEFAULT_EXPR)
  _set_default(table_name="jobs", column_name="created_at", expression=_STRING_DEFAULT_EXPR)
  _set_default(table_name="jobs", column_name="updated_at", expression=_STRING_DEFAULT_EXPR)

  # Ensure DB-level create defaults exist for timestamp updated_at fields.
  for table_name in _TIMESTAMP_UPDATED_AT_TABLES:
    _set_default(table_name=table_name, column_name="updated_at", expression="now()")

  # Attach DB-level update automation for timestamp updated_at fields.
  for table_name in _TIMESTAMP_UPDATED_AT_TABLES:
    _create_update_trigger(table_name=table_name, trigger_name=f"trg_{table_name}_set_updated_at", function_name="set_updated_at_timestamptz")

  # Attach DB-level update automation for legacy text updated_at fields.
  _create_update_trigger(table_name="jobs", trigger_name="trg_jobs_set_updated_at", function_name="set_updated_at_iso8601_text")


def downgrade() -> None:
  """Downgrade schema."""
  # Drop triggers conservatively to keep downgrade safe for partial schemas.
  for table_name in _TIMESTAMP_UPDATED_AT_TABLES:
    if table_exists(table_name=table_name):
      op.execute(f'DROP TRIGGER IF EXISTS "trg_{table_name}_set_updated_at" ON "{table_name}"')
  if table_exists(table_name="jobs"):
    op.execute('DROP TRIGGER IF EXISTS "trg_jobs_set_updated_at" ON "jobs"')

  # Drop helper trigger functions.
  op.execute("DROP FUNCTION IF EXISTS public.set_updated_at_iso8601_text()")
  op.execute("DROP FUNCTION IF EXISTS public.set_updated_at_timestamptz()")

  # Use guarded_* helpers so downgrade steps are idempotent when re-run.
  # ### commands auto generated by Alembic - please adjust! ###
  guarded_drop_index("ux_web_push_subscriptions_endpoint", table_name="web_push_subscriptions")
  guarded_drop_index(op.f("ix_web_push_subscriptions_user_id"), table_name="web_push_subscriptions")
  guarded_drop_table("web_push_subscriptions")
  guarded_drop_table("user_usage_metrics")
  guarded_drop_index(op.f("ix_user_usage_logs_user_id"), table_name="user_usage_logs")
  guarded_drop_table("user_usage_logs")
  guarded_drop_index(op.f("ix_user_tier_overrides_user_id"), table_name="user_tier_overrides")
  guarded_drop_table("user_tier_overrides")
  guarded_drop_index(op.f("ix_user_quota_reservations_user_id"), table_name="user_quota_reservations")
  guarded_drop_index(op.f("ix_user_quota_reservations_metric_key"), table_name="user_quota_reservations")
  guarded_drop_index(op.f("ix_user_quota_reservations_job_id"), table_name="user_quota_reservations")
  guarded_drop_table("user_quota_reservations")
  guarded_drop_index(op.f("ix_user_quota_buckets_user_id"), table_name="user_quota_buckets")
  guarded_drop_index(op.f("ix_user_quota_buckets_metric_key"), table_name="user_quota_buckets")
  guarded_drop_table("user_quota_buckets")
  guarded_drop_index(op.f("ix_user_feature_flag_overrides_user_id"), table_name="user_feature_flag_overrides")
  guarded_drop_index(op.f("ix_user_feature_flag_overrides_feature_flag_id"), table_name="user_feature_flag_overrides")
  guarded_drop_table("user_feature_flag_overrides")
  guarded_drop_index(op.f("ix_subjective_input_widgets_section_id"), table_name="subjective_input_widgets")
  guarded_drop_table("subjective_input_widgets")
  guarded_drop_index(op.f("ix_section_illustrations_section_id"), table_name="section_illustrations")
  guarded_drop_index(op.f("ix_section_illustrations_illustration_id"), table_name="section_illustrations")
  guarded_drop_table("section_illustrations")
  guarded_drop_index(op.f("ix_section_errors_section_id"), table_name="section_errors")
  guarded_drop_table("section_errors")
  guarded_drop_index("ux_runtime_config_values_user", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'USER'"))
  guarded_drop_index("ux_runtime_config_values_tier", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'TIER'"))
  guarded_drop_index("ux_runtime_config_values_tenant", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'TENANT'"))
  guarded_drop_index("ux_runtime_config_values_global", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'GLOBAL'"))
  guarded_drop_index(op.f("ix_runtime_config_values_user_id"), table_name="runtime_config_values")
  guarded_drop_index(op.f("ix_runtime_config_values_subscription_tier_id"), table_name="runtime_config_values")
  guarded_drop_index(op.f("ix_runtime_config_values_scope"), table_name="runtime_config_values")
  guarded_drop_index(op.f("ix_runtime_config_values_org_id"), table_name="runtime_config_values")
  guarded_drop_index(op.f("ix_runtime_config_values_key"), table_name="runtime_config_values")
  guarded_drop_table("runtime_config_values")
  guarded_drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
  guarded_drop_index(op.f("ix_notifications_template_id"), table_name="notifications")
  guarded_drop_table("notifications")
  guarded_drop_table("llm_audit_logs")
  guarded_drop_index(op.f("ix_email_delivery_logs_user_id"), table_name="email_delivery_logs")
  guarded_drop_index(op.f("ix_email_delivery_logs_to_address"), table_name="email_delivery_logs")
  guarded_drop_index(op.f("ix_email_delivery_logs_template_id"), table_name="email_delivery_logs")
  guarded_drop_index(op.f("ix_email_delivery_logs_provider_request_id"), table_name="email_delivery_logs")
  guarded_drop_index(op.f("ix_email_delivery_logs_provider_message_id"), table_name="email_delivery_logs")
  guarded_drop_table("email_delivery_logs")
  guarded_drop_index(op.f("ix_data_transfer_runs_status"), table_name="data_transfer_runs")
  guarded_drop_index(op.f("ix_data_transfer_runs_source_export_run_id"), table_name="data_transfer_runs")
  guarded_drop_index(op.f("ix_data_transfer_runs_run_type"), table_name="data_transfer_runs")
  guarded_drop_index(op.f("ix_data_transfer_runs_requested_by"), table_name="data_transfer_runs")
  guarded_drop_index(op.f("ix_data_transfer_runs_job_id"), table_name="data_transfer_runs")
  guarded_drop_table("data_transfer_runs")
  guarded_drop_index(op.f("ix_users_org_id"), table_name="users")
  guarded_drop_index(op.f("ix_users_firebase_uid"), table_name="users")
  guarded_drop_index(op.f("ix_users_email"), table_name="users")
  guarded_drop_table("users")
  guarded_drop_table("subscription_tier_feature_flags")
  guarded_drop_index(op.f("ix_sections_lesson_id"), table_name="sections")
  guarded_drop_table("sections")
  guarded_drop_table("role_permissions")
  guarded_drop_table("organization_feature_flags")
  guarded_drop_table("subscription_tiers")
  guarded_drop_table("roles")
  guarded_drop_table("permissions")
  guarded_drop_table("organizations")
  guarded_drop_table("llm_call_audit")
  guarded_drop_index(op.f("ix_lessons_user_id"), table_name="lessons")
  guarded_drop_index(op.f("ix_lessons_idempotency_key"), table_name="lessons")
  guarded_drop_table("lessons")
  guarded_drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
  guarded_drop_index(op.f("ix_jobs_section_id"), table_name="jobs")
  guarded_drop_index(op.f("ix_jobs_parent_job_id"), table_name="jobs")
  guarded_drop_index(op.f("ix_jobs_lesson_id"), table_name="jobs")
  guarded_drop_index(op.f("ix_jobs_job_kind"), table_name="jobs")
  guarded_drop_index(op.f("ix_jobs_idempotency_key"), table_name="jobs")
  guarded_drop_table("jobs")
  guarded_drop_index(op.f("ix_illustrations_storage_object_name"), table_name="illustrations")
  guarded_drop_table("illustrations")
  guarded_drop_table("fenster_widgets")
  guarded_drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
  guarded_drop_table("feature_flags")
  guarded_drop_index(op.f("ix_tutor_audios_job_id"), table_name="tutor_audios")
  guarded_drop_index(op.f("ix_tutor_audios_id"), table_name="tutor_audios")
  guarded_drop_table("tutor_audios")
  # ### end Alembic commands ###
