"""baseline

Revision ID: 3055a1cfd37e
Revises:
Create Date: 2026-02-04 03:36:31.418179

"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import insert

# revision identifiers, used by Alembic.
revision: str = "3055a1cfd37e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "coach_audios",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("section_number", sa.Integer(), nullable=False),
    sa.Column("subsection_index", sa.Integer(), nullable=False),
    sa.Column("text_content", sa.Text(), nullable=True),
    sa.Column("audio_data", sa.LargeBinary(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_coach_audios_id"), "coach_audios", ["id"], unique=False)
  op.create_index(op.f("ix_coach_audios_job_id"), "coach_audios", ["job_id"], unique=False)
  op.create_table(
    "feature_flags",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("default_enabled", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
  op.create_table(
    "fenster_widgets",
    sa.Column("fenster_id", sa.Uuid(), nullable=False),
    sa.Column("type", sa.Enum("INLINE_BLOB", "CDN_URL", name="fensterwidgettype"), nullable=False),
    sa.Column("content", sa.LargeBinary(), nullable=True),
    sa.Column("url", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("fenster_id"),
  )
  op.create_table(
    "jobs",
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("target_agent", sa.String(), nullable=True),
    sa.Column("phase", sa.String(), nullable=False),
    sa.Column("subphase", sa.String(), nullable=True),
    sa.Column("expected_sections", sa.Integer(), nullable=True),
    sa.Column("completed_sections", sa.Integer(), nullable=True),
    sa.Column("completed_section_indexes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("current_section_index", sa.Integer(), nullable=True),
    sa.Column("current_section_status", sa.String(), nullable=True),
    sa.Column("current_section_retry_count", sa.Integer(), nullable=True),
    sa.Column("current_section_title", sa.String(), nullable=True),
    sa.Column("retry_count", sa.Integer(), nullable=True),
    sa.Column("max_retries", sa.Integer(), nullable=True),
    sa.Column("retry_sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("retry_agents", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("retry_parent_job_id", sa.String(), nullable=True),
    sa.Column("total_steps", sa.Integer(), nullable=True),
    sa.Column("completed_steps", sa.Integer(), nullable=True),
    sa.Column("progress", sa.Double(), nullable=True),
    sa.Column("logs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.String(), nullable=False),
    sa.Column("updated_at", sa.String(), nullable=False),
    sa.Column("completed_at", sa.String(), nullable=True),
    sa.Column("ttl", sa.Integer(), nullable=True),
    sa.Column("idempotency_key", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("job_id"),
  )
  op.create_index(op.f("ix_jobs_idempotency_key"), "jobs", ["idempotency_key"], unique=False)
  op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
  op.create_table(
    "lessons",
    sa.Column("lesson_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("topic", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("created_at", sa.String(), nullable=False),
    sa.Column("schema_version", sa.String(), nullable=False),
    sa.Column("prompt_version", sa.String(), nullable=False),
    sa.Column("provider_a", sa.String(), nullable=False),
    sa.Column("model_a", sa.String(), nullable=False),
    sa.Column("provider_b", sa.String(), nullable=False),
    sa.Column("model_b", sa.String(), nullable=False),
    sa.Column("lesson_json", sa.Text(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("latency_ms", sa.Integer(), nullable=False),
    sa.Column("idempotency_key", sa.String(), nullable=True),
    sa.Column("tags", sa.ARRAY(sa.Text()), nullable=True),
    sa.Column("is_archived", sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint("lesson_id"),
  )
  op.create_index(op.f("ix_lessons_idempotency_key"), "lessons", ["idempotency_key"], unique=False)
  op.create_index(op.f("ix_lessons_user_id"), "lessons", ["user_id"], unique=False)
  op.create_table(
    "llm_call_audit",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("timestamp_request", sa.DateTime(timezone=True), nullable=False),
    sa.Column("timestamp_response", sa.DateTime(timezone=True), nullable=True),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("duration_ms", sa.Integer(), nullable=False),
    sa.Column("agent", sa.String(), nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("model", sa.String(), nullable=False),
    sa.Column("lesson_topic", sa.String(), nullable=True),
    sa.Column("request_payload", sa.Text(), nullable=False),
    sa.Column("response_payload", sa.Text(), nullable=True),
    sa.Column("prompt_tokens", sa.Integer(), nullable=True),
    sa.Column("completion_tokens", sa.Integer(), nullable=True),
    sa.Column("total_tokens", sa.Integer(), nullable=True),
    sa.Column("request_type", sa.String(), nullable=False),
    sa.Column("purpose", sa.String(), nullable=True),
    sa.Column("call_index", sa.String(), nullable=True),
    sa.Column("job_id", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "organizations",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  op.create_table(
    "permissions",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("slug", sa.String(), nullable=False),
    sa.Column("display_name", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("slug"),
  )
  op.create_table(
    "roles",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("level", sa.Enum("GLOBAL", "TENANT", name="role_level"), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  op.create_table(
    "subscription_tiers",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("max_file_upload_kb", sa.Integer(), nullable=True),
    sa.Column("highest_lesson_depth", sa.Enum("highlights", "detailed", "training", name="lesson_depth"), nullable=True),
    sa.Column("max_sections_per_lesson", sa.Integer(), nullable=True),
    sa.Column("file_upload_quota", sa.Integer(), nullable=True),
    sa.Column("image_upload_quota", sa.Integer(), nullable=True),
    sa.Column("gen_sections_quota", sa.Integer(), nullable=True),
    sa.Column("research_quota", sa.Integer(), nullable=True),
    sa.Column("concurrent_lesson_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_research_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_writing_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_coach_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("coach_mode_enabled", sa.Boolean(), nullable=False),
    sa.Column("coach_voice_tier", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  op.create_table(
    "organization_feature_flags",
    sa.Column("org_id", sa.Uuid(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.PrimaryKeyConstraint("org_id", "feature_flag_id"),
  )
  op.create_table(
    "role_permissions",
    sa.Column("role_id", sa.Uuid(), nullable=False),
    sa.Column("permission_id", sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"]),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
    sa.PrimaryKeyConstraint("role_id", "permission_id"),
  )
  op.create_table(
    "subscription_tier_feature_flags",
    sa.Column("subscription_tier_id", sa.Integer(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.PrimaryKeyConstraint("subscription_tier_id", "feature_flag_id"),
  )
  op.create_table(
    "users",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("firebase_uid", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=True),
    sa.Column("provider", sa.String(), nullable=True),
    sa.Column("role_id", sa.Uuid(), nullable=False),
    sa.Column("org_id", sa.Uuid(), nullable=True),
    sa.Column("status", sa.Enum("PENDING", "APPROVED", "DISABLED", "REJECTED", name="user_status"), nullable=False),
    sa.Column("auth_method", sa.Enum("GOOGLE_SSO", "NATIVE", name="auth_method"), nullable=False),
    sa.Column("profession", sa.String(), nullable=True),
    sa.Column("city", sa.String(), nullable=True),
    sa.Column("country", sa.String(), nullable=True),
    sa.Column("age", sa.Integer(), nullable=True),
    sa.Column("photo_url", sa.String(), nullable=True),
    sa.Column("gender", sa.String(), nullable=True),
    sa.Column("gender_other", sa.String(), nullable=True),
    sa.Column("occupation", sa.String(), nullable=True),
    sa.Column("topics_of_interest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("intended_use", sa.String(), nullable=True),
    sa.Column("intended_use_other", sa.String(), nullable=True),
    sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
    sa.Column("accepted_terms_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("accepted_privacy_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("terms_version", sa.String(), nullable=True),
    sa.Column("privacy_version", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
  op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
  op.create_table(
    "email_delivery_logs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=True),
    sa.Column("to_address", sa.String(), nullable=False),
    sa.Column("template_id", sa.String(), nullable=False),
    sa.Column("placeholders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("provider_message_id", sa.String(), nullable=True),
    sa.Column("provider_request_id", sa.String(), nullable=True),
    sa.Column("provider_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_email_delivery_logs_provider_message_id"), "email_delivery_logs", ["provider_message_id"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_provider_request_id"), "email_delivery_logs", ["provider_request_id"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_template_id"), "email_delivery_logs", ["template_id"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_to_address"), "email_delivery_logs", ["to_address"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_user_id"), "email_delivery_logs", ["user_id"], unique=False)
  op.create_table(
    "llm_audit_logs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("prompt_summary", sa.Text(), nullable=True),
    sa.Column("model_name", sa.String(), nullable=False),
    sa.Column("tokens_used", sa.Integer(), nullable=True),
    sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("status", sa.String(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "runtime_config_values",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key", sa.String(), nullable=False),
    sa.Column("scope", sa.Enum("GLOBAL", "TIER", "TENANT", "USER", name="runtime_config_scope"), nullable=False),
    sa.Column("org_id", sa.Uuid(), nullable=True),
    sa.Column("subscription_tier_id", sa.Integer(), nullable=True),
    sa.Column("user_id", sa.Uuid(), nullable=True),
    sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_runtime_config_values_key"), "runtime_config_values", ["key"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_org_id"), "runtime_config_values", ["org_id"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_scope"), "runtime_config_values", ["scope"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_subscription_tier_id"), "runtime_config_values", ["subscription_tier_id"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_user_id"), "runtime_config_values", ["user_id"], unique=False)
  op.create_index("ux_runtime_config_values_global", "runtime_config_values", ["key"], unique=True, postgresql_where=sa.text("scope = 'GLOBAL'"))
  op.create_index("ux_runtime_config_values_tenant", "runtime_config_values", ["key", "org_id"], unique=True, postgresql_where=sa.text("scope = 'TENANT'"))
  op.create_index("ux_runtime_config_values_tier", "runtime_config_values", ["key", "subscription_tier_id"], unique=True, postgresql_where=sa.text("scope = 'TIER'"))
  op.create_index("ux_runtime_config_values_user", "runtime_config_values", ["key", "user_id"], unique=True, postgresql_where=sa.text("scope = 'USER'"))
  op.create_table(
    "user_quota_buckets",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("metric_key", sa.String(), nullable=False),
    sa.Column("period", postgresql.ENUM("WEEK", "MONTH", name="quota_period"), nullable=False),
    sa.Column("period_start", sa.Date(), nullable=False),
    sa.Column("used", sa.BigInteger(), server_default="0", nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_user_quota_buckets_metric_key"), "user_quota_buckets", ["metric_key"], unique=False)
  op.create_index(op.f("ix_user_quota_buckets_user_id"), "user_quota_buckets", ["user_id"], unique=False)
  op.create_table(
    "user_tier_overrides",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("max_file_upload_kb", sa.Integer(), nullable=True),
    sa.Column("file_upload_quota", sa.Integer(), nullable=True),
    sa.Column("image_upload_quota", sa.Integer(), nullable=True),
    sa.Column("gen_sections_quota", sa.Integer(), nullable=True),
    sa.Column("research_quota", sa.Integer(), nullable=True),
    sa.Column("concurrent_lesson_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_research_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_writing_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_coach_limit", sa.Integer(), nullable=True),
    sa.Column("coach_mode_enabled", sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_user_tier_overrides_user_id"), "user_tier_overrides", ["user_id"], unique=False)
  op.create_table(
    "user_usage_logs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("action_type", sa.String(), nullable=False),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_user_usage_logs_user_id"), "user_usage_logs", ["user_id"], unique=False)
  op.create_table(
    "user_usage_metrics",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("subscription_tier_id", sa.Integer(), nullable=False),
    sa.Column("files_uploaded_count", sa.Integer(), nullable=False),
    sa.Column("images_uploaded_count", sa.Integer(), nullable=False),
    sa.Column("sections_generated_count", sa.Integer(), nullable=False),
    sa.Column("research_usage_count", sa.Integer(), nullable=False),
    sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("user_id"),
  )
  # Seed required reference data so auth/quota code paths never 500 on a fresh DB.
  # Use fixed UUIDs so environments stay consistent after local resets.
  role_super_admin_id = uuid.UUID("3e56ebfc-1d62-42cb-a920-ab6e916e58bf")
  role_org_admin_id = uuid.UUID("102d6fab-322c-48f8-a8f8-0d9e5eb52aa6")
  role_org_member_id = uuid.UUID("d028adea-31a6-48fb-afd8-777a4cd410b4")
  permission_user_manage_id = uuid.UUID("2fcaeb8d-9824-4506-953a-c5e949db3db8")
  roles_table = sa.table("roles", sa.column("id"), sa.column("name"), sa.column("level"), sa.column("description"))
  permissions_table = sa.table("permissions", sa.column("id"), sa.column("slug"), sa.column("display_name"), sa.column("description"))
  role_permissions_table = sa.table("role_permissions", sa.column("role_id"), sa.column("permission_id"))
  subscription_tiers_table = sa.table(
    "subscription_tiers",
    sa.column("name"),
    sa.column("max_file_upload_kb"),
    sa.column("highest_lesson_depth"),
    sa.column("max_sections_per_lesson"),
    sa.column("file_upload_quota"),
    sa.column("image_upload_quota"),
    sa.column("gen_sections_quota"),
    sa.column("research_quota"),
    sa.column("coach_mode_enabled"),
    sa.column("coach_voice_tier"),
  )
  op.execute(
    insert(roles_table)
    .values(
      [
        {"id": role_super_admin_id, "name": "Super Admin", "level": "GLOBAL", "description": "Global administrator."},
        {"id": role_org_admin_id, "name": "Org Admin", "level": "TENANT", "description": "Organization administrator."},
        {"id": role_org_member_id, "name": "Org Member", "level": "TENANT", "description": "Default role for new users."},
      ]
    )
    .on_conflict_do_nothing(index_elements=["name"])
  )
  op.execute(insert(permissions_table).values([{"id": permission_user_manage_id, "slug": "user:manage", "display_name": "Manage Users", "description": "List users and update roles/statuses."}]).on_conflict_do_nothing(index_elements=["slug"]))
  op.execute(insert(role_permissions_table).values([{"role_id": role_super_admin_id, "permission_id": permission_user_manage_id}]).on_conflict_do_nothing(index_elements=["role_id", "permission_id"]))
  op.execute(
    insert(subscription_tiers_table)
    .values(
      [
        {
          "name": "Free",
          "max_file_upload_kb": 512,
          "highest_lesson_depth": "highlights",
          "max_sections_per_lesson": 2,
          "file_upload_quota": 0,
          "image_upload_quota": 0,
          "gen_sections_quota": 20,
          "research_quota": None,
          "coach_mode_enabled": False,
          "coach_voice_tier": "none",
        },
        {
          "name": "Plus",
          "max_file_upload_kb": 1024,
          "highest_lesson_depth": "detailed",
          "max_sections_per_lesson": 6,
          "file_upload_quota": 5,
          "image_upload_quota": 5,
          "gen_sections_quota": 100,
          "research_quota": None,
          "coach_mode_enabled": True,
          "coach_voice_tier": "device",
        },
        {
          "name": "Pro",
          "max_file_upload_kb": 2048,
          "highest_lesson_depth": "training",
          "max_sections_per_lesson": 10,
          "file_upload_quota": 10,
          "image_upload_quota": 10,
          "gen_sections_quota": 250,
          "research_quota": None,
          "coach_mode_enabled": True,
          "coach_voice_tier": "premium",
        },
      ]
    )
    .on_conflict_do_nothing(index_elements=["name"])
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table("user_usage_metrics")
  op.drop_index(op.f("ix_user_usage_logs_user_id"), table_name="user_usage_logs")
  op.drop_table("user_usage_logs")
  op.drop_index(op.f("ix_user_tier_overrides_user_id"), table_name="user_tier_overrides")
  op.drop_table("user_tier_overrides")
  op.drop_index(op.f("ix_user_quota_buckets_user_id"), table_name="user_quota_buckets")
  op.drop_index(op.f("ix_user_quota_buckets_metric_key"), table_name="user_quota_buckets")
  op.drop_table("user_quota_buckets")
  op.drop_index("ux_runtime_config_values_user", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'USER'"))
  op.drop_index("ux_runtime_config_values_tier", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'TIER'"))
  op.drop_index("ux_runtime_config_values_tenant", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'TENANT'"))
  op.drop_index("ux_runtime_config_values_global", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'GLOBAL'"))
  op.drop_index(op.f("ix_runtime_config_values_user_id"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_subscription_tier_id"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_scope"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_org_id"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_key"), table_name="runtime_config_values")
  op.drop_table("runtime_config_values")
  op.drop_table("llm_audit_logs")
  op.drop_index(op.f("ix_email_delivery_logs_user_id"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_to_address"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_template_id"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_provider_request_id"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_provider_message_id"), table_name="email_delivery_logs")
  op.drop_table("email_delivery_logs")
  op.drop_index(op.f("ix_users_org_id"), table_name="users")
  op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  op.drop_table("subscription_tier_feature_flags")
  op.drop_table("role_permissions")
  op.drop_table("organization_feature_flags")
  op.drop_table("subscription_tiers")
  op.drop_table("roles")
  op.drop_table("permissions")
  op.drop_table("organizations")
  op.drop_table("llm_call_audit")
  op.drop_index(op.f("ix_lessons_user_id"), table_name="lessons")
  op.drop_index(op.f("ix_lessons_idempotency_key"), table_name="lessons")
  op.drop_table("lessons")
  op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_idempotency_key"), table_name="jobs")
  op.drop_table("jobs")
  op.drop_table("fenster_widgets")
  op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
  op.drop_table("feature_flags")
  op.drop_index(op.f("ix_coach_audios_job_id"), table_name="coach_audios")
  op.drop_index(op.f("ix_coach_audios_id"), table_name="coach_audios")
  op.drop_table("coach_audios")
  # ### end Alembic commands ###
