"""auto_migration_20260129_211032

Revision ID: 3a2bfc86881f
Revises: 6f6e9c1c0c0a
Create Date: 2026-01-29 21:10:51.606619

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a2bfc86881f"
down_revision: str | Sequence[str] | None = "6f6e9c1c0c0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(op.f("feature_flags_key_key"), "feature_flags", type_="unique")
  op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
  op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
  op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=False)
  op.create_unique_constraint(op.f("feature_flags_key_key"), "feature_flags", ["key"], postgresql_nulls_not_distinct=False)
  # ### end Alembic commands ###
