"""initial_schema_baseline

Revision ID: 939e5e69b348
Revises:
Create Date: 2026-02-14 03:20:21.690928

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "939e5e69b348"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # Use guarded_* helpers so migrations are idempotent on existing schemas.
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "ascii_diagrams",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_ascii_diagrams_creator_id"), "ascii_diagrams", ["creator_id"], unique=False)
  op.create_table(
    "checklists",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_checklists_creator_id"), "checklists", ["creator_id"], unique=False)
  op.create_table(
    "code_editors",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_code_editors_creator_id"), "code_editors", ["creator_id"], unique=False)
  op.create_table(
    "compares",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_compares_creator_id"), "compares", ["creator_id"], unique=False)
  op.create_table(
    "feature_flags",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("default_enabled", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
  op.create_table(
    "fensters",
    sa.Column("fenster_id", sa.Uuid(), nullable=False),
    sa.Column("public_id", sa.String(), nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("type", sa.Enum("INLINE_BLOB", "CDN_URL", name="fensterwidgettype"), nullable=False),
    sa.Column("content", sa.LargeBinary(), nullable=True),
    sa.Column("url", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("fenster_id"),
  )
  op.create_index(op.f("ix_fensters_creator_id"), "fensters", ["creator_id"], unique=False)
  op.create_index(op.f("ix_fensters_public_id"), "fensters", ["public_id"], unique=True)
  op.create_table(
    "fill_blanks",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_fill_blanks_creator_id"), "fill_blanks", ["creator_id"], unique=False)
  op.create_table(
    "flipcards",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_flipcards_creator_id"), "flipcards", ["creator_id"], unique=False)
  op.create_table(
    "free_texts",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("ai_prompt", sa.Text(), nullable=False),
    sa.Column("wordlist", sa.Text(), nullable=True),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_free_texts_creator_id"), "free_texts", ["creator_id"], unique=False)
  op.create_table(
    "illustrations",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("public_id", sa.String(), nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("storage_bucket", sa.Text(), nullable=False),
    sa.Column("storage_object_name", sa.Text(), nullable=False),
    sa.Column("mime_type", sa.String(), nullable=False),
    sa.Column("caption", sa.Text(), nullable=False),
    sa.Column("ai_prompt", sa.Text(), nullable=False),
    sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("regenerate", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_illustrations_creator_id"), "illustrations", ["creator_id"], unique=False)
  op.create_index(op.f("ix_illustrations_public_id"), "illustrations", ["public_id"], unique=True)
  op.create_index(op.f("ix_illustrations_storage_object_name"), "illustrations", ["storage_object_name"], unique=False)
  op.create_table(
    "input_lines",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("ai_prompt", sa.Text(), nullable=False),
    sa.Column("wordlist", sa.Text(), nullable=True),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_input_lines_creator_id"), "input_lines", ["creator_id"], unique=False)
  op.create_table(
    "interactive_terminals",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_interactive_terminals_creator_id"), "interactive_terminals", ["creator_id"], unique=False)
  op.create_table(
    "jobs",
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("root_job_id", sa.String(), nullable=False),
    sa.Column("resume_source_job_id", sa.String(), nullable=True),
    sa.Column("superseded_by_job_id", sa.String(), nullable=True),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("job_kind", sa.String(), nullable=False),
    sa.Column("request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("parent_job_id", sa.String(), nullable=True),
    sa.Column("lesson_id", sa.String(), nullable=True),
    sa.Column("section_id", sa.Integer(), nullable=True),
    sa.Column("target_agent", sa.String(), nullable=True),
    sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("error_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("idempotency_key", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("job_id"),
    sa.UniqueConstraint("user_id", "job_kind", "idempotency_key", name="ux_jobs_user_kind_idempotency"),
  )
  op.create_index(op.f("ix_jobs_idempotency_key"), "jobs", ["idempotency_key"], unique=False)
  op.create_index(op.f("ix_jobs_job_kind"), "jobs", ["job_kind"], unique=False)
  op.create_index(op.f("ix_jobs_lesson_id"), "jobs", ["lesson_id"], unique=False)
  op.create_index(op.f("ix_jobs_parent_job_id"), "jobs", ["parent_job_id"], unique=False)
  op.create_index(op.f("ix_jobs_resume_source_job_id"), "jobs", ["resume_source_job_id"], unique=False)
  op.create_index(op.f("ix_jobs_root_job_id"), "jobs", ["root_job_id"], unique=False)
  op.create_index(op.f("ix_jobs_section_id"), "jobs", ["section_id"], unique=False)
  op.create_index(op.f("ix_jobs_superseded_by_job_id"), "jobs", ["superseded_by_job_id"], unique=False)
  op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
  op.create_index("ux_jobs_active_resume_source", "jobs", ["resume_source_job_id"], unique=True, postgresql_where=sa.text("resume_source_job_id IS NOT NULL AND status IN ('queued', 'running')"))
  op.create_table(
    "lesson_requests",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("topic", sa.Text(), nullable=False),
    sa.Column("details", sa.Text(), nullable=True),
    sa.Column("outcomes_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("blueprint", sa.String(), nullable=False),
    sa.Column("teaching_style_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("learner_level", sa.String(), nullable=True),
    sa.Column("depth", sa.String(), nullable=False),
    sa.Column("lesson_language", sa.String(), nullable=False),
    sa.Column("secondary_language", sa.String(), nullable=True),
    sa.Column("widgets_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_lesson_requests_creator_id"), "lesson_requests", ["creator_id"], unique=False)
  op.create_table(
    "llm_call_audit",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("timestamp_request", sa.DateTime(timezone=True), nullable=False),
    sa.Column("timestamp_response", sa.DateTime(timezone=True), nullable=True),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("duration_ms", sa.Integer(), nullable=False),
    sa.Column("agent", sa.String(), nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("model", sa.String(), nullable=False),
    sa.Column("lesson_topic", sa.String(), nullable=True),
    sa.Column("request_payload", sa.Text(), nullable=False),
    sa.Column("response_payload", sa.Text(), nullable=True),
    sa.Column("prompt_tokens", sa.Integer(), nullable=True),
    sa.Column("completion_tokens", sa.Integer(), nullable=True),
    sa.Column("total_tokens", sa.Integer(), nullable=True),
    sa.Column("request_type", sa.String(), nullable=False),
    sa.Column("purpose", sa.String(), nullable=True),
    sa.Column("call_index", sa.String(), nullable=True),
    sa.Column("job_id", sa.String(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "llm_model_pricing",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("model", sa.String(), nullable=False),
    sa.Column("input_per_1m", sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column("output_per_1m", sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("provider", "model", name="ux_llm_model_pricing_provider_model"),
  )
  op.create_index(op.f("ix_llm_model_pricing_model"), "llm_model_pricing", ["model"], unique=False)
  op.create_index(op.f("ix_llm_model_pricing_provider"), "llm_model_pricing", ["provider"], unique=False)
  op.create_table(
    "markdowns",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_markdowns_creator_id"), "markdowns", ["creator_id"], unique=False)
  op.create_table(
    "mcqs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_mcqs_creator_id"), "mcqs", ["creator_id"], unique=False)
  op.create_table(
    "organizations",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  op.create_table(
    "permissions",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("slug", sa.String(), nullable=False),
    sa.Column("display_name", sa.String(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("slug"),
  )
  op.create_table(
    "roles",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("level", sa.Enum("GLOBAL", "TENANT", name="role_level"), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  op.create_table(
    "step_flows",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_step_flows_creator_id"), "step_flows", ["creator_id"], unique=False)
  op.create_table(
    "subscription_tiers",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("is_tenant_tier", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("max_file_upload_kb", sa.Integer(), nullable=True),
    sa.Column("highest_lesson_depth", sa.Enum("highlights", "detailed", "training", name="lesson_depth"), nullable=True),
    sa.Column("max_sections_per_lesson", sa.Integer(), nullable=True),
    sa.Column("file_upload_quota", sa.Integer(), nullable=True),
    sa.Column("image_upload_quota", sa.Integer(), nullable=True),
    sa.Column("gen_sections_quota", sa.Integer(), nullable=True),
    sa.Column("research_quota", sa.Integer(), nullable=True),
    sa.Column("concurrent_lesson_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_research_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_writing_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("concurrent_tutor_limit", sa.Integer(), server_default="1", nullable=True),
    sa.Column("tutor_mode_enabled", sa.Boolean(), nullable=False),
    sa.Column("tutor_voice_tier", sa.String(), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("name"),
  )
  op.create_table(
    "swipe_cards",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_swipe_cards_creator_id"), "swipe_cards", ["creator_id"], unique=False)
  op.create_table(
    "tables_data",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_tables_data_creator_id"), "tables_data", ["creator_id"], unique=False)
  op.create_table(
    "terminal_demos",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_terminal_demos_creator_id"), "terminal_demos", ["creator_id"], unique=False)
  op.create_table(
    "translations",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_translations_creator_id"), "translations", ["creator_id"], unique=False)
  op.create_table(
    "treeviews",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_treeviews_creator_id"), "treeviews", ["creator_id"], unique=False)
  op.create_table(
    "tutors",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("creator_id", sa.String(), nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("section_number", sa.Integer(), nullable=False),
    sa.Column("subsection_index", sa.Integer(), nullable=False),
    sa.Column("text_content", sa.Text(), nullable=True),
    sa.Column("audio_data", sa.LargeBinary(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_tutors_creator_id"), "tutors", ["creator_id"], unique=False)
  op.create_index(op.f("ix_tutors_id"), "tutors", ["id"], unique=False)
  op.create_index(op.f("ix_tutors_job_id"), "tutors", ["job_id"], unique=False)
  op.create_table(
    "job_checkpoints",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("stage", sa.String(), nullable=False),
    sa.Column("section_index", sa.Integer(), nullable=True),
    sa.Column("state", sa.String(), nullable=False),
    sa.Column("artifact_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("attempt_count", sa.Integer(), nullable=False),
    sa.Column("last_error", sa.Text(), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_job_checkpoints_job_id"), "job_checkpoints", ["job_id"], unique=False)
  op.create_index(op.f("ix_job_checkpoints_state"), "job_checkpoints", ["state"], unique=False)
  op.create_index("ux_job_checkpoints_job_stage_null", "job_checkpoints", ["job_id", "stage"], unique=True, postgresql_where=sa.text("section_index IS NULL"))
  op.create_index("ux_job_checkpoints_job_stage_section_not_null", "job_checkpoints", ["job_id", "stage", "section_index"], unique=True, postgresql_where=sa.text("section_index IS NOT NULL"))
  op.create_table(
    "job_events",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("event_type", sa.String(), nullable=False),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_job_events_event_type"), "job_events", ["event_type"], unique=False)
  op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
  op.create_table(
    "lessons",
    sa.Column("lesson_id", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=True),
    sa.Column("topic", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("created_at", sa.String(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"')"), nullable=False),
    sa.Column("schema_version", sa.String(), nullable=False),
    sa.Column("prompt_version", sa.String(), nullable=False),
    sa.Column("provider_a", sa.String(), nullable=False),
    sa.Column("model_a", sa.String(), nullable=False),
    sa.Column("provider_b", sa.String(), nullable=False),
    sa.Column("model_b", sa.String(), nullable=False),
    sa.Column("lesson_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("lesson_request_id", sa.Integer(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("latency_ms", sa.Integer(), nullable=False),
    sa.Column("idempotency_key", sa.String(), nullable=True),
    sa.Column("tags", sa.ARRAY(sa.Text()), nullable=True),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.ForeignKeyConstraint(["lesson_request_id"], ["lesson_requests.id"]),
    sa.PrimaryKeyConstraint("lesson_id"),
  )
  op.create_index(op.f("ix_lessons_idempotency_key"), "lessons", ["idempotency_key"], unique=False)
  op.create_index(op.f("ix_lessons_lesson_request_id"), "lessons", ["lesson_request_id"], unique=False)
  op.create_index(op.f("ix_lessons_user_id"), "lessons", ["user_id"], unique=False)
  op.create_table(
    "organization_feature_flags",
    sa.Column("org_id", sa.Uuid(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.PrimaryKeyConstraint("org_id", "feature_flag_id"),
  )
  op.create_table(
    "role_permissions",
    sa.Column("role_id", sa.Uuid(), nullable=False),
    sa.Column("permission_id", sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"]),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
    sa.PrimaryKeyConstraint("role_id", "permission_id"),
  )
  op.create_table(
    "subscription_tier_feature_flags",
    sa.Column("subscription_tier_id", sa.Integer(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.PrimaryKeyConstraint("subscription_tier_id", "feature_flag_id"),
  )
  op.create_table(
    "users",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("firebase_uid", sa.String(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=True),
    sa.Column("provider", sa.String(), nullable=True),
    sa.Column("role_id", sa.Uuid(), nullable=False),
    sa.Column("org_id", sa.Uuid(), nullable=True),
    sa.Column("status", sa.Enum("PENDING", "APPROVED", "DISABLED", "REJECTED", name="user_status"), nullable=False),
    sa.Column("auth_method", sa.Enum("GOOGLE_SSO", "NATIVE", name="auth_method"), nullable=False),
    sa.Column("profession", sa.String(), nullable=True),
    sa.Column("city", sa.String(), nullable=True),
    sa.Column("country", sa.String(), nullable=True),
    sa.Column("age", sa.Integer(), nullable=True),
    sa.Column("photo_url", sa.String(), nullable=True),
    sa.Column("gender", sa.String(), nullable=True),
    sa.Column("gender_other", sa.String(), nullable=True),
    sa.Column("occupation", sa.String(), nullable=True),
    sa.Column("topics_of_interest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("intended_use", sa.String(), nullable=True),
    sa.Column("intended_use_other", sa.String(), nullable=True),
    sa.Column("primary_language", sa.String(), nullable=True),
    sa.Column("secondary_language", sa.String(), nullable=True),
    sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("archived_by", sa.Uuid(), nullable=True),
    sa.Column("accepted_terms_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("accepted_privacy_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("terms_version", sa.String(), nullable=True),
    sa.Column("privacy_version", sa.String(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
  op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
  op.create_table(
    "data_transfer_runs",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("run_type", sa.String(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("requested_by", sa.UUID(), nullable=False),
    sa.Column("source_export_run_id", sa.UUID(), nullable=True),
    sa.Column("include_illustrations", sa.Boolean(), nullable=False),
    sa.Column("include_audios", sa.Boolean(), nullable=False),
    sa.Column("include_fensters", sa.Boolean(), nullable=False),
    sa.Column("separate_zips", sa.Boolean(), nullable=False),
    sa.Column("dry_run", sa.Boolean(), nullable=False),
    sa.Column("password_plaintext", sa.Text(), nullable=False),
    sa.Column("gcs_bucket", sa.String(), nullable=False),
    sa.Column("artifacts_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("filters_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("idempotency_key", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["requested_by"], ["users.id"]),
    sa.ForeignKeyConstraint(["source_export_run_id"], ["data_transfer_runs.id"]),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("run_type", "requested_by", "idempotency_key", name="ux_data_transfer_runs_type_user_idempotency"),
  )
  op.create_index(op.f("ix_data_transfer_runs_job_id"), "data_transfer_runs", ["job_id"], unique=True)
  op.create_index(op.f("ix_data_transfer_runs_requested_by"), "data_transfer_runs", ["requested_by"], unique=False)
  op.create_index(op.f("ix_data_transfer_runs_run_type"), "data_transfer_runs", ["run_type"], unique=False)
  op.create_index(op.f("ix_data_transfer_runs_source_export_run_id"), "data_transfer_runs", ["source_export_run_id"], unique=False)
  op.create_index(op.f("ix_data_transfer_runs_status"), "data_transfer_runs", ["status"], unique=False)
  op.create_table(
    "email_delivery_logs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=True),
    sa.Column("to_address", sa.String(), nullable=False),
    sa.Column("template_id", sa.String(), nullable=False),
    sa.Column("placeholders", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("provider", sa.String(), nullable=False),
    sa.Column("provider_message_id", sa.String(), nullable=True),
    sa.Column("provider_request_id", sa.String(), nullable=True),
    sa.Column("provider_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_email_delivery_logs_provider_message_id"), "email_delivery_logs", ["provider_message_id"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_provider_request_id"), "email_delivery_logs", ["provider_request_id"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_template_id"), "email_delivery_logs", ["template_id"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_to_address"), "email_delivery_logs", ["to_address"], unique=False)
  op.create_index(op.f("ix_email_delivery_logs_user_id"), "email_delivery_logs", ["user_id"], unique=False)
  op.create_table(
    "llm_audit_logs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("prompt_summary", sa.Text(), nullable=True),
    sa.Column("model_name", sa.String(), nullable=False),
    sa.Column("tokens_used", sa.Integer(), nullable=True),
    sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("status", sa.String(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "notifications",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("template_id", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("body", sa.Text(), nullable=False),
    sa.Column("data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("read", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_notifications_template_id"), "notifications", ["template_id"], unique=False)
  op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
  op.create_table(
    "runtime_config_values",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("key", sa.String(), nullable=False),
    sa.Column("scope", sa.Enum("GLOBAL", "TIER", "TENANT", "USER", name="runtime_config_scope"), nullable=False),
    sa.Column("org_id", sa.Uuid(), nullable=True),
    sa.Column("subscription_tier_id", sa.Integer(), nullable=True),
    sa.Column("user_id", sa.Uuid(), nullable=True),
    sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["org_id"], ["organizations.id"]),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_runtime_config_values_key"), "runtime_config_values", ["key"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_org_id"), "runtime_config_values", ["org_id"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_scope"), "runtime_config_values", ["scope"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_subscription_tier_id"), "runtime_config_values", ["subscription_tier_id"], unique=False)
  op.create_index(op.f("ix_runtime_config_values_user_id"), "runtime_config_values", ["user_id"], unique=False)
  op.create_index("ux_runtime_config_values_global", "runtime_config_values", ["key"], unique=True, postgresql_where=sa.text("scope = 'GLOBAL'"))
  op.create_index("ux_runtime_config_values_tenant", "runtime_config_values", ["key", "org_id"], unique=True, postgresql_where=sa.text("scope = 'TENANT'"))
  op.create_index("ux_runtime_config_values_tier", "runtime_config_values", ["key", "subscription_tier_id"], unique=True, postgresql_where=sa.text("scope = 'TIER'"))
  op.create_index("ux_runtime_config_values_user", "runtime_config_values", ["key", "user_id"], unique=True, postgresql_where=sa.text("scope = 'USER'"))
  op.create_table(
    "sections",
    sa.Column("section_id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("lesson_id", sa.String(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("order_index", sa.Integer(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("content_shorthand", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("removed_widgets_csv", sa.Text(), nullable=True),
    sa.Column("illustration_id", sa.BigInteger(), nullable=True),
    sa.Column("markdown_id", sa.Integer(), nullable=True),
    sa.Column("tutor_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["illustration_id"], ["illustrations.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["lesson_id"], ["lessons.lesson_id"]),
    sa.ForeignKeyConstraint(["markdown_id"], ["markdowns.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["tutor_id"], ["tutors.id"], ondelete="SET NULL"),
    sa.PrimaryKeyConstraint("section_id"),
    sa.UniqueConstraint("lesson_id", "order_index", name="ux_sections_lesson_order_index"),
  )
  op.create_index(op.f("ix_sections_illustration_id"), "sections", ["illustration_id"], unique=False)
  op.create_index(op.f("ix_sections_lesson_id"), "sections", ["lesson_id"], unique=False)
  op.create_index(op.f("ix_sections_markdown_id"), "sections", ["markdown_id"], unique=False)
  op.create_index(op.f("ix_sections_tutor_id"), "sections", ["tutor_id"], unique=False)
  op.create_table(
    "user_feature_flag_overrides",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("starts_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["feature_flag_id"], ["feature_flags.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "feature_flag_id", name="ux_user_feature_flag_overrides_user_flag"),
  )
  op.create_index(op.f("ix_user_feature_flag_overrides_feature_flag_id"), "user_feature_flag_overrides", ["feature_flag_id"], unique=False)
  op.create_index(op.f("ix_user_feature_flag_overrides_user_id"), "user_feature_flag_overrides", ["user_id"], unique=False)
  op.create_table(
    "user_quota_buckets",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("metric_key", sa.String(), nullable=False),
    sa.Column("period", postgresql.ENUM("WEEK", "MONTH", name="quota_period"), nullable=False),
    sa.Column("period_start", sa.Date(), nullable=False),
    sa.Column("used", sa.BigInteger(), server_default="0", nullable=False),
    sa.Column("reserved", sa.BigInteger(), server_default="0", nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_user_quota_buckets_metric_key"), "user_quota_buckets", ["metric_key"], unique=False)
  op.create_index(op.f("ix_user_quota_buckets_user_id"), "user_quota_buckets", ["user_id"], unique=False)
  op.create_table(
    "user_quota_reservations",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("metric_key", sa.String(), nullable=False),
    sa.Column("period", postgresql.ENUM("WEEK", "MONTH", name="quota_period"), nullable=False),
    sa.Column("period_start", sa.Date(), nullable=False),
    sa.Column("quantity", sa.BigInteger(), server_default="1", nullable=False),
    sa.Column("job_id", sa.String(), nullable=False),
    sa.Column("section_index", sa.Integer(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("user_id", "metric_key", "period", "period_start", "job_id", "section_index", name="ux_quota_reservation_key"),
  )
  op.create_index(op.f("ix_user_quota_reservations_job_id"), "user_quota_reservations", ["job_id"], unique=False)
  op.create_index(op.f("ix_user_quota_reservations_metric_key"), "user_quota_reservations", ["metric_key"], unique=False)
  op.create_index(op.f("ix_user_quota_reservations_user_id"), "user_quota_reservations", ["user_id"], unique=False)
  op.create_table(
    "user_tier_overrides",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("max_file_upload_kb", sa.Integer(), nullable=True),
    sa.Column("file_upload_quota", sa.Integer(), nullable=True),
    sa.Column("image_upload_quota", sa.Integer(), nullable=True),
    sa.Column("gen_sections_quota", sa.Integer(), nullable=True),
    sa.Column("research_quota", sa.Integer(), nullable=True),
    sa.Column("concurrent_lesson_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_research_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_writing_limit", sa.Integer(), nullable=True),
    sa.Column("concurrent_tutor_limit", sa.Integer(), nullable=True),
    sa.Column("tutor_mode_enabled", sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_user_tier_overrides_user_id"), "user_tier_overrides", ["user_id"], unique=False)
  op.create_table(
    "user_usage_logs",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("action_type", sa.String(), nullable=False),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_user_usage_logs_user_id"), "user_usage_logs", ["user_id"], unique=False)
  op.create_table(
    "user_usage_metrics",
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("subscription_tier_id", sa.Integer(), nullable=False),
    sa.Column("files_uploaded_count", sa.Integer(), nullable=False),
    sa.Column("images_uploaded_count", sa.Integer(), nullable=False),
    sa.Column("sections_generated_count", sa.Integer(), nullable=False),
    sa.Column("research_usage_count", sa.Integer(), nullable=False),
    sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.ForeignKeyConstraint(["subscription_tier_id"], ["subscription_tiers.id"]),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
    sa.PrimaryKeyConstraint("user_id"),
  )
  op.create_table(
    "web_push_subscriptions",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("user_id", sa.UUID(), nullable=False),
    sa.Column("endpoint", sa.Text(), nullable=False),
    sa.Column("p256dh", sa.Text(), nullable=False),
    sa.Column("auth", sa.Text(), nullable=False),
    sa.Column("user_agent", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_web_push_subscriptions_user_id"), "web_push_subscriptions", ["user_id"], unique=False)
  op.create_index("ux_web_push_subscriptions_endpoint", "web_push_subscriptions", ["endpoint"], unique=True)
  op.create_table(
    "section_errors",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("section_id", sa.Integer(), nullable=False),
    sa.Column("error_index", sa.Integer(), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=False),
    sa.Column("error_path", sa.Text(), nullable=True),
    sa.Column("section_scope", sa.String(), nullable=True),
    sa.Column("subsection_index", sa.Integer(), nullable=True),
    sa.Column("item_index", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_section_errors_section_id"), "section_errors", ["section_id"], unique=False)
  op.create_table(
    "subsections",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("section_id", sa.Integer(), nullable=False),
    sa.Column("subsection_index", sa.Integer(), nullable=False),
    sa.Column("subsection_title", sa.Text(), nullable=False),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("section_id", "subsection_index", name="ux_subsections_section_subsection_index"),
  )
  op.create_index(op.f("ix_subsections_section_id"), "subsections", ["section_id"], unique=False)
  op.create_table(
    "subsection_widgets",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("public_id", sa.String(), nullable=False),
    sa.Column("subsection_id", sa.Integer(), nullable=False),
    sa.Column("widget_id", sa.String(), nullable=True),
    sa.Column("widget_index", sa.Integer(), nullable=False),
    sa.Column(
      "widget_type",
      sa.Enum(
        "markdown",
        "flipcards",
        "tr",
        "fillblank",
        "table",
        "compare",
        "swipecards",
        "freeText",
        "inputLine",
        "stepFlow",
        "asciiDiagram",
        "checklist",
        "interactiveTerminal",
        "terminalDemo",
        "codeEditor",
        "treeview",
        "mcqs",
        "fenster",
        "illustration",
        name="subsection_widget_type",
      ),
      nullable=False,
    ),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["subsection_id"], ["subsections.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("public_id", name="ux_subsection_widgets_public_id"),
    sa.UniqueConstraint("subsection_id", "widget_index", "widget_type", name="ux_subsection_widgets_subsection_widget_index_type"),
  )
  op.create_index(op.f("ix_subsection_widgets_public_id"), "subsection_widgets", ["public_id"], unique=False)
  op.create_index(op.f("ix_subsection_widgets_subsection_id"), "subsection_widgets", ["subsection_id"], unique=False)
  op.create_table(
    "tutor_fragments",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("tutor_id", sa.Integer(), nullable=False),
    sa.Column("fragment_id", sa.Text(), nullable=False),
    sa.Column("section_id", sa.Integer(), nullable=True),
    sa.Column("subsection_id", sa.Integer(), nullable=True),
    sa.Column("status", sa.String(), nullable=False),
    sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["section_id"], ["sections.section_id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["subsection_id"], ["subsections.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["tutor_id"], ["tutors.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_tutor_fragments_fragment_id"), "tutor_fragments", ["fragment_id"], unique=False)
  op.create_index(op.f("ix_tutor_fragments_section_id"), "tutor_fragments", ["section_id"], unique=False)
  op.create_index(op.f("ix_tutor_fragments_subsection_id"), "tutor_fragments", ["subsection_id"], unique=False)
  op.create_index(op.f("ix_tutor_fragments_tutor_id"), "tutor_fragments", ["tutor_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # Use guarded_* helpers so downgrade steps are idempotent when re-run.
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_tutor_fragments_tutor_id"), table_name="tutor_fragments")
  op.drop_index(op.f("ix_tutor_fragments_subsection_id"), table_name="tutor_fragments")
  op.drop_index(op.f("ix_tutor_fragments_section_id"), table_name="tutor_fragments")
  op.drop_index(op.f("ix_tutor_fragments_fragment_id"), table_name="tutor_fragments")
  op.drop_table("tutor_fragments")
  op.drop_index(op.f("ix_subsection_widgets_subsection_id"), table_name="subsection_widgets")
  op.drop_index(op.f("ix_subsection_widgets_public_id"), table_name="subsection_widgets")
  op.drop_table("subsection_widgets")
  op.drop_index(op.f("ix_subsections_section_id"), table_name="subsections")
  op.drop_table("subsections")
  op.drop_index(op.f("ix_section_errors_section_id"), table_name="section_errors")
  op.drop_table("section_errors")
  op.drop_index("ux_web_push_subscriptions_endpoint", table_name="web_push_subscriptions")
  op.drop_index(op.f("ix_web_push_subscriptions_user_id"), table_name="web_push_subscriptions")
  op.drop_table("web_push_subscriptions")
  op.drop_table("user_usage_metrics")
  op.drop_index(op.f("ix_user_usage_logs_user_id"), table_name="user_usage_logs")
  op.drop_table("user_usage_logs")
  op.drop_index(op.f("ix_user_tier_overrides_user_id"), table_name="user_tier_overrides")
  op.drop_table("user_tier_overrides")
  op.drop_index(op.f("ix_user_quota_reservations_user_id"), table_name="user_quota_reservations")
  op.drop_index(op.f("ix_user_quota_reservations_metric_key"), table_name="user_quota_reservations")
  op.drop_index(op.f("ix_user_quota_reservations_job_id"), table_name="user_quota_reservations")
  op.drop_table("user_quota_reservations")
  op.drop_index(op.f("ix_user_quota_buckets_user_id"), table_name="user_quota_buckets")
  op.drop_index(op.f("ix_user_quota_buckets_metric_key"), table_name="user_quota_buckets")
  op.drop_table("user_quota_buckets")
  op.drop_index(op.f("ix_user_feature_flag_overrides_user_id"), table_name="user_feature_flag_overrides")
  op.drop_index(op.f("ix_user_feature_flag_overrides_feature_flag_id"), table_name="user_feature_flag_overrides")
  op.drop_table("user_feature_flag_overrides")
  op.drop_index(op.f("ix_sections_tutor_id"), table_name="sections")
  op.drop_index(op.f("ix_sections_markdown_id"), table_name="sections")
  op.drop_index(op.f("ix_sections_lesson_id"), table_name="sections")
  op.drop_index(op.f("ix_sections_illustration_id"), table_name="sections")
  op.drop_table("sections")
  op.drop_index("ux_runtime_config_values_user", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'USER'"))
  op.drop_index("ux_runtime_config_values_tier", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'TIER'"))
  op.drop_index("ux_runtime_config_values_tenant", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'TENANT'"))
  op.drop_index("ux_runtime_config_values_global", table_name="runtime_config_values", postgresql_where=sa.text("scope = 'GLOBAL'"))
  op.drop_index(op.f("ix_runtime_config_values_user_id"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_subscription_tier_id"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_scope"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_org_id"), table_name="runtime_config_values")
  op.drop_index(op.f("ix_runtime_config_values_key"), table_name="runtime_config_values")
  op.drop_table("runtime_config_values")
  op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
  op.drop_index(op.f("ix_notifications_template_id"), table_name="notifications")
  op.drop_table("notifications")
  op.drop_table("llm_audit_logs")
  op.drop_index(op.f("ix_email_delivery_logs_user_id"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_to_address"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_template_id"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_provider_request_id"), table_name="email_delivery_logs")
  op.drop_index(op.f("ix_email_delivery_logs_provider_message_id"), table_name="email_delivery_logs")
  op.drop_table("email_delivery_logs")
  op.drop_index(op.f("ix_data_transfer_runs_status"), table_name="data_transfer_runs")
  op.drop_index(op.f("ix_data_transfer_runs_source_export_run_id"), table_name="data_transfer_runs")
  op.drop_index(op.f("ix_data_transfer_runs_run_type"), table_name="data_transfer_runs")
  op.drop_index(op.f("ix_data_transfer_runs_requested_by"), table_name="data_transfer_runs")
  op.drop_index(op.f("ix_data_transfer_runs_job_id"), table_name="data_transfer_runs")
  op.drop_table("data_transfer_runs")
  op.drop_index(op.f("ix_users_org_id"), table_name="users")
  op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  op.drop_table("subscription_tier_feature_flags")
  op.drop_table("role_permissions")
  op.drop_table("organization_feature_flags")
  op.drop_index(op.f("ix_lessons_user_id"), table_name="lessons")
  op.drop_index(op.f("ix_lessons_lesson_request_id"), table_name="lessons")
  op.drop_index(op.f("ix_lessons_idempotency_key"), table_name="lessons")
  op.drop_table("lessons")
  op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
  op.drop_index(op.f("ix_job_events_event_type"), table_name="job_events")
  op.drop_table("job_events")
  op.drop_index("ux_job_checkpoints_job_stage_section_not_null", table_name="job_checkpoints", postgresql_where=sa.text("section_index IS NOT NULL"))
  op.drop_index("ux_job_checkpoints_job_stage_null", table_name="job_checkpoints", postgresql_where=sa.text("section_index IS NULL"))
  op.drop_index(op.f("ix_job_checkpoints_state"), table_name="job_checkpoints")
  op.drop_index(op.f("ix_job_checkpoints_job_id"), table_name="job_checkpoints")
  op.drop_table("job_checkpoints")
  op.drop_index(op.f("ix_tutors_job_id"), table_name="tutors")
  op.drop_index(op.f("ix_tutors_id"), table_name="tutors")
  op.drop_index(op.f("ix_tutors_creator_id"), table_name="tutors")
  op.drop_table("tutors")
  op.drop_index(op.f("ix_treeviews_creator_id"), table_name="treeviews")
  op.drop_table("treeviews")
  op.drop_index(op.f("ix_translations_creator_id"), table_name="translations")
  op.drop_table("translations")
  op.drop_index(op.f("ix_terminal_demos_creator_id"), table_name="terminal_demos")
  op.drop_table("terminal_demos")
  op.drop_index(op.f("ix_tables_data_creator_id"), table_name="tables_data")
  op.drop_table("tables_data")
  op.drop_index(op.f("ix_swipe_cards_creator_id"), table_name="swipe_cards")
  op.drop_table("swipe_cards")
  op.drop_table("subscription_tiers")
  op.drop_index(op.f("ix_step_flows_creator_id"), table_name="step_flows")
  op.drop_table("step_flows")
  op.drop_table("roles")
  op.drop_table("permissions")
  op.drop_table("organizations")
  op.drop_index(op.f("ix_mcqs_creator_id"), table_name="mcqs")
  op.drop_table("mcqs")
  op.drop_index(op.f("ix_markdowns_creator_id"), table_name="markdowns")
  op.drop_table("markdowns")
  op.drop_index(op.f("ix_llm_model_pricing_provider"), table_name="llm_model_pricing")
  op.drop_index(op.f("ix_llm_model_pricing_model"), table_name="llm_model_pricing")
  op.drop_table("llm_model_pricing")
  op.drop_table("llm_call_audit")
  op.drop_index(op.f("ix_lesson_requests_creator_id"), table_name="lesson_requests")
  op.drop_table("lesson_requests")
  op.drop_index("ux_jobs_active_resume_source", table_name="jobs", postgresql_where=sa.text("resume_source_job_id IS NOT NULL AND status IN ('queued', 'running')"))
  op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_superseded_by_job_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_section_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_root_job_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_resume_source_job_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_parent_job_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_lesson_id"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_job_kind"), table_name="jobs")
  op.drop_index(op.f("ix_jobs_idempotency_key"), table_name="jobs")
  op.drop_table("jobs")
  op.drop_index(op.f("ix_interactive_terminals_creator_id"), table_name="interactive_terminals")
  op.drop_table("interactive_terminals")
  op.drop_index(op.f("ix_input_lines_creator_id"), table_name="input_lines")
  op.drop_table("input_lines")
  op.drop_index(op.f("ix_illustrations_storage_object_name"), table_name="illustrations")
  op.drop_index(op.f("ix_illustrations_public_id"), table_name="illustrations")
  op.drop_index(op.f("ix_illustrations_creator_id"), table_name="illustrations")
  op.drop_table("illustrations")
  op.drop_index(op.f("ix_free_texts_creator_id"), table_name="free_texts")
  op.drop_table("free_texts")
  op.drop_index(op.f("ix_flipcards_creator_id"), table_name="flipcards")
  op.drop_table("flipcards")
  op.drop_index(op.f("ix_fill_blanks_creator_id"), table_name="fill_blanks")
  op.drop_table("fill_blanks")
  op.drop_index(op.f("ix_fensters_public_id"), table_name="fensters")
  op.drop_index(op.f("ix_fensters_creator_id"), table_name="fensters")
  op.drop_table("fensters")
  op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
  op.drop_table("feature_flags")
  op.drop_index(op.f("ix_compares_creator_id"), table_name="compares")
  op.drop_table("compares")
  op.drop_index(op.f("ix_code_editors_creator_id"), table_name="code_editors")
  op.drop_table("code_editors")
  op.drop_index(op.f("ix_checklists_creator_id"), table_name="checklists")
  op.drop_table("checklists")
  op.drop_index(op.f("ix_ascii_diagrams_creator_id"), table_name="ascii_diagrams")
  op.drop_table("ascii_diagrams")
  # ### end Alembic commands ###
