"""markdown widget

Revision ID: 93e25e6216fa
Revises: 30bf37f6dee4
Create Date: 2026-02-03 04:07:08.671504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93e25e6216fa"
down_revision: str | Sequence[str] | None = "30bf37f6dee4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column("users", "onboarding_completed", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column("users", "onboarding_completed", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  # ### end Alembic commands ###
