"""add feature flag permissions

Revision ID: a73c0f9a24a9
Revises: 02d553f1f3c0
Create Date: 2026-02-15 09:25:28.119912

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a73c0f9a24a9"
down_revision: str | Sequence[str] | None = "02d553f1f3c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # empty: allow
  # Use guarded_* helpers so migrations are idempotent on existing schemas.
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # Use guarded_* helpers so downgrade steps are idempotent when re-run.
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
