"""outcomes_and_tasks_auth_update

Revision ID: bf687b4cfbed
Revises: a9c4d2e7f1b6
Create Date: 2026-02-12 13:30:01.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.core.migration_guards import guarded_create_index, guarded_drop_index

# revision identifiers, used by Alembic.
revision: str = "bf687b4cfbed"
down_revision: str | Sequence[str] | None = "a9c4d2e7f1b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # Use guarded_* helpers so migrations are idempotent on existing schemas.
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column("ascii_diagrams", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("ascii_diagrams", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("checklists", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("checklists", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("code_editors", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("code_editors", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("compares", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("compares", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("fensters", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("fensters", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("fill_blanks", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("fill_blanks", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("flipcards", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("flipcards", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("free_texts", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("free_texts", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("input_lines", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("input_lines", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("interactive_terminals", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("interactive_terminals", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("job_checkpoints", "attempt_count", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False)
  op.alter_column("lesson_requests", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("lesson_requests", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("markdowns", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("markdowns", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("mcqs", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("mcqs", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("step_flows", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("step_flows", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("subsection_widgets", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("subsection_widgets", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  guarded_drop_index(op.f("ix_subsection_widgets_public_id"), table_name="subsection_widgets")
  guarded_create_index(op.f("ix_subsection_widgets_public_id"), "subsection_widgets", ["public_id"], unique=False)
  op.alter_column("subsections", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("subsections", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("swipe_cards", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("swipe_cards", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("tables_data", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("tables_data", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("terminal_demos", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("terminal_demos", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("translations", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("translations", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("treeviews", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("treeviews", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("tutor_fragments", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("tutor_fragments", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  op.alter_column("tutors", "status", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
  op.alter_column("tutors", "is_archived", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  guarded_drop_index(op.f("ix_tutor_audios_creator_id"), table_name="tutors")
  guarded_drop_index(op.f("ix_tutor_audios_id"), table_name="tutors")
  guarded_drop_index(op.f("ix_tutor_audios_job_id"), table_name="tutors")
  op.alter_column("users", "is_discarded", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # Use guarded_* helpers so downgrade steps are idempotent when re-run.
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column("users", "is_discarded", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  guarded_create_index(op.f("ix_tutor_audios_job_id"), "tutors", ["job_id"], unique=False)
  guarded_create_index(op.f("ix_tutor_audios_id"), "tutors", ["id"], unique=False)
  guarded_create_index(op.f("ix_tutor_audios_creator_id"), "tutors", ["creator_id"], unique=False)
  op.alter_column("tutors", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("tutors", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("tutor_fragments", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("tutor_fragments", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("treeviews", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("treeviews", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("translations", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("translations", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("terminal_demos", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("terminal_demos", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("tables_data", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("tables_data", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("swipe_cards", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("swipe_cards", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("subsections", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("subsections", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  guarded_drop_index(op.f("ix_subsection_widgets_public_id"), table_name="subsection_widgets")
  guarded_create_index(op.f("ix_subsection_widgets_public_id"), "subsection_widgets", ["public_id"], unique=True)
  op.alter_column("subsection_widgets", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("subsection_widgets", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("step_flows", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("step_flows", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("mcqs", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("mcqs", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("markdowns", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("markdowns", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("lesson_requests", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("lesson_requests", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'queued'::character varying"), existing_nullable=False)
  op.alter_column("job_checkpoints", "attempt_count", existing_type=sa.INTEGER(), server_default=sa.text("0"), existing_nullable=False)
  op.alter_column("interactive_terminals", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("interactive_terminals", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("input_lines", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("input_lines", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("free_texts", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("free_texts", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("flipcards", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("flipcards", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("fill_blanks", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("fill_blanks", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("fensters", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("fensters", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("compares", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("compares", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("code_editors", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("code_editors", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("checklists", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("checklists", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  op.alter_column("ascii_diagrams", "is_archived", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False)
  op.alter_column("ascii_diagrams", "status", existing_type=sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), existing_nullable=False)
  # ### end Alembic commands ###
